### ISSUE TITLE
Group 21: Assignment 1

### ISSUE THREAD

**Issue by ChristianPeus** [sebastianbarfort/sds#11]
## Some packages we will need later on:

library("readr")
library("plyr")
library("dplyr")
library("lubridate")
library("ggplot2")
library("stringr")
library("zoo")
library("scales")
## Create a new dataframe of the stock of paintings at MOMA for each month in the year.
# Read the data

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# We check if we can find Paintings

Paintings = distinct(select(df, Classification))
# Filter out observations that include Classification=="Painting" (The task is: "Stock of paintings(!)")

df_paintings=filter(df,Classification == "Painting")
# Create year and month-variable

df_paintings = mutate(df_paintings,
                      year=str_sub(df_paintings$DateAcquired,start = 1, end = 4), 
                      month=str_sub(df_paintings$DateAcquired, start = 6, end = 7),
                      ym=substr(df_paintings$DateAcquired, start=1, stop=7))
# Converts year and month-variables from characters to numeric values and arrange obs in ascending order

df_paintings$year <- as.numeric(df_paintings$year)
df_paintings$month <- as.numeric(df_paintings$month)
df_paintings$ym <- as.yearmon(df_paintings$ym)
df_paintings = arrange(df_paintings,-desc(year), -desc(month))
# Group data by year and month

by_year_month = group_by(df_paintings, ym, year, month)

detach("package:plyr", unload=TRUE)
# New dataset with the new variable 'count' counting the number of new aquired paintings pr month/year

by_year_month = summarise(by_year_month, count = n())

by_year_month$cumsum = cumsum(by_year_month$count)
## Use ggplot2 and your new data frame to plot the the stock of paintings on the y-axis and the date on the x-axis.

p = ggplot(by_year_month, aes(x = as.Date(ym), y = cumsum))
p + geom_line(name="Stock", colour = "#ee4d4d") + theme_minimal() +
  labs(list(title = "Stock of paintings from 1930 - 2015", x = "Year", y = "Stock of paintings")) + 
  theme(plot.title = element_text(lineheight=.8, face="bold"))
# We used geom_line, because it gives a good and easy overview of the development of the stock of paintings.
## Create the same plot but this time the color should reflect the stock of paintings for curator approved and non-curator approved paintings, respectively

by_year_month_Cur  = group_by(df_paintings, ym, CuratorApproved)
by_year_month_Cur = summarise(by_year_month_Cur, count = n())
by_year_month_Cur$cumsum = cumsum(by_year_month_Cur$count)
# Plotting data

p = ggplot(by_year_month_Cur, aes(x = as.Date(ym), y = cumsum))
p + geom_line(aes(colour = CuratorApproved)) + theme_minimal() +
  labs(list(title = "Stock of paintings pr. year and month", x = "Year", y = "Stock of paintings"))+
  theme(plot.title = element_text(lineheight=.8, face="bold"))
## Create a new dataframe of the stock of paintings grouped by what department the painting belongs to
# Aggregating stock of paintings by year, month and Department

by_year_month_Dep  = group_by(df_paintings, Department, ym)
by_year_month_Dep = summarise(by_year_month_Dep, count = n())
by_year_month_Dep$cumsum = cumsum(by_year_month_Dep$count)

by_year_month_Dep=group_by(by_year_month_Dep, Department)
by_year_month_Dep=mutate(by_year_month_Dep, cumsum_Depart = cumsum(cumsum))
## Therefore, we plot the new paintings, MoMa gets in every year / the time period

ggplot(by_year_month_Dep, aes(x = as.Date(ym), fill = Department)) + 
  geom_bar(color = "black", position = "dodge") + 
  scale_x_date(labels = date_format("%Y"), breaks = "10 years") +
  labs(title = "Stock of Paintings from 1929 - 2015 / New paintings in the time period", x = "Year", y = "Stock of Paintings") + 
  theme(plot.title = element_text(lineheight=.5, face="bold"))  
# Alternative:

ggplot(by_year_month_Dep, aes(x = as.Date(ym)))+
  geom_freqpoly(aes(colour = Department)) + 
  scale_x_date(labels = date_format("%Y"), breaks = "10 years") +
  labs(title = "MOMA Stock of Paintings 1929 - 2015 / New paintings in the time period", x = "Year", y = "Stock of Paintings") +
  theme(plot.title = element_text(lineheight=.5, face="bold"))
# -> The highest increase in their stock of paintings has had "Painting & Sculpture".
## Write a piece of code that counts the number of paintings by each artist in the dataset. List the 10 painters with the highest number of paintings in MOMAÃ¢ÂÂs collection.

by_year_month_Art=group_by(df_paintings, Artist)
by_year_month_Art=summarise(by_year_month_Art, count=n())
by_year_month_Art=arrange(by_year_month_Art, desc(count)) %>%
  top_n(n=10)
## create a world map where each country is colored according to the stock of paintings in MOMA's collection using the variable "ArtistBio".
# We recognized, that this column consists of various informations (birthdate, nationality, birthplace etc.) -everytime in a completely different order.
# The only proof, where the artist is born, is the declaration after the word "born". You cannot conclude the birthplace from the nationality. (It might often be the case - but not everytime!)
# Therefore, we decided to use the following way.

library("stringr")

birthplace = gsub("[\(\)]", "", regmatches(df_paintings$ArtistBio, gregexpr("\(.*?\)", df_paintings$ArtistBio))) # remove the brackets
birthplace = gsub("[0-9]", "", birthplace) # remove any kind of numbers
birthplace = gsub("\,","",birthplace) # remove the commas

birthplace = str_extract(birthplace, "born[:space:][[a-zA-Z]?[:space:][a-zA-Z]?[:space:][a-zA-Z]]*") # extract everything that comes after born
birthplace = gsub("born ", "", birthplace) # remove the word "born" and the space after it
# Now we have to rename some countries/cities/words, so that it is possible to join it with the map-data

birthplace = gsub("Korea", "South Korea", birthplace)
birthplace = gsub("in Beirut Lebanon", "Lebanon", birthplace)
birthplace = gsub("Belorussia now Belarus", "Belarus", birthplace)
birthplace = gsub("Russia now Latvia", "Latvia", birthplace)
birthplace = gsub("Scotland", "UK", birthplace)
birthplace = gsub("Tunis", "Tunisia", birthplace)
birthplace = gsub("Germany Alsace", "France", birthplace)
birthplace = gsub("the Netherlands", "Netherlands", birthplace)
birthplace = gsub("The Philipines", "Philippines", birthplace)
birthplace = gsub("Great Britain", "UK", birthplace)
birthplace = gsub("England", "UK", birthplace)
# It looks good but we need to remove the blank space after all country-names.

birthplace = gsub(" ", "", birthplace)
birthplace = gsub("SouthKorea", "South Korea", birthplace) # This leads to another problem. South Korea consits of more than one word. We rename it "by hand"

birth = cbind(df_paintings, birthplace)
birth = na.omit(birth)
birth  = group_by(birth, birthplace)
birthplace = summarise(birth, count = n())
birthplace = birthplace[-c(1, 37),] # remove the row with no entries and the row "U" (we can't use gsub("U"), because then it would change every "u".)
# Create a new entry "birthplace = USA, count = 1" instead of the row with "U"

countries = data.frame(cbind(c("USA"),c(1)))
colnames(countries) = c("birthplace","count")
birthplace = rbind(birthplace, countries)

birthplace$count = as.numeric(birthplace$count)

map = map_data("world")
# Visualization:

library("dplyr")

library("countrycode")
birthplace$iso2c = countrycode(birthplace$birthplace, origin = "country.name", destination = "iso2c")
map$iso2c = countrycode(map$region, origin = "country.name", destination = "iso2c")
df.map.2 = full_join(birthplace, map) # merge data by iso2c

p = ggplot(df.map.2, aes(x = long, y = lat, group = group, fill = count))
p + geom_polygon() +
  expand_limits(x = df.map.2$long, y = df.map.2$lat) +
  labs(title = "World map where each country is colored according to the stock of paintings in MOMA's collection") +
  theme(plot.title = element_text(lineheight=.5, face="bold"))
## We extract what's in the paranteses, and put them into seperate variables

colnames(df_paintings)[1] <- "Title"
area_paintings = select(df_paintings,Dimensions, Classification, Title, Artist)
# Remove or change some things, that would cause problems later on

area_paintings$Dimensions = gsub("Framed 47.5 x 37.3 cm", "(47.5 x 37.3 cm)", area_paintings$Dimensions)
area_paintings$Dimensions = gsub("10 x 14 cm", "(10 x 14 cm)", area_paintings$Dimensions)
area_paintings$Dimensions = gsub("(274.3.x 182.9 cm)", "(274.3 x 182.9 cm)", area_paintings$Dimensions)
area_paintings$Dimensions = gsub("(cm)", " ", area_paintings$Dimensions) # remove "cm"
area_paintings$Dimensions = gsub(")", " )", area_paintings$Dimensions)

area_paintings$Dim_Num = str_extract(area_paintings$Dimensions, "([\U0028][0-9].+)") # extract everything in the brackets
area_paintings$Dim_Num1  = str_extract(area_paintings$Dim_Num, "([0-9]_[0-9][.]_[0-9]_[0-9].)|[0-9]+") # extract the length
area_paintings$Dim_Num2  = str_extract(str_extract(area_paintings$Dim_Num, "([:alpha:]_[ ]_[ ][0-9].+)"), "([0-9]_[0-9][.]_[0-9]_[0-9].)|[0-9]+") # extract the width
# Create numeric entries:

area_paintings$Dim_Num1 = as.numeric(area_paintings$Dim_Num1)
area_paintings$Dim_Num2 = as.numeric(area_paintings$Dim_Num2)
# Create the area (in cm²)

area_paintings$area = area_paintings$Dim_Num1 \* area_paintings$Dim_Num2
# Take care about the "diameters":

circle = subset(area_paintings, is.na(area_paintings$Dim_Num2))

circle$area =  pi \* ((circle$Dim_Num1)/2)^2 # The formula of a circle-area is: pi*r²

circle = circle[-c(18,28),] # Remove two rows with unspecific dimensions

area_paintings= rbind(area_paintings, circle)

area_paintings = subset(area_paintings, !is.na(area_paintings$area)) #remove rows with NA in the area-column
# Create the Top 5:

area_paintings = area_paintings[order(-area_paintings$area, decreasing = FALSE),] #order it in an increasing way

Dimension = c("Largest", "2nd largest", "3rd largest", "4th largest", "5th largest", "5th smallest", "4th smallest", "3rd smallest", "2nd smallest", "Smallest")

top5 = rbind(head(area_paintings, n = 5), tail(area_paintings, n= 5))
top5 = cbind(top5, Dimension)
top5 = top5[-c(1,2,5)]

**Comment by sebastianbarfort** [comment]
Good job. 

Nice use of `dplyr` verbs, but consider using the pipe operator (`%>%`). I think it makes for much more readable code (see slides for examples). 

For histograms, remember to use `fill` instead of `colour`. 

I like the use of `geom_freqpoly`. 

I like the way you approach question 8 - although it's slightly inefficient :)

**APPROVED**
