### ISSUE TITLE
Group 13: Assignment 1

### ISSUE THREAD

**Issue by ettemegnal** [sebastianbarfort/sds#13]
# Q1

library("readr")
library("dplyr")
library("lubridate")
# Read the data

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# Make a new dataframe only with paintings:

df1=subset(df,Classification=="Painting")
# Make two new variables, year and month, using the existing DateAcquired

df1$Year=year(df1$DateAcquired)
df1$Month=months(df1$DateAcquired)
# Creating a dataframe of the stock of paintings for each month in the year

df.1=df1%>%
  group_by(Year,Month, CuratorApproved)%>%
  summarise(numberofpaints = n())
# Q2

library("ggplot2")
# Plotting the stock of paintings with the date on the x-axis
# We choose the bar plot, because we are plotting the stock of paintings, which is an amount.
# Therefore it makes sence to  plot a filled bar instead of a line, which is better suited for a flow variable.

p = ggplot(df.1, aes(x = Year))
p + geom_bar(stat = "bin", colour = "red")+ ggtitle("Number of paints pr year")+labs(x="Time",y="Number of painting")
# Q3

library("ggplot2")
# Creating the same plot, but now the blue color reflects the stock of paintings for curator approved and the red color reflects the non-curator approved paintings

p = ggplot(df.1, aes(x = Year,  fill = factor(CuratorApproved)))
p = p + geom_bar(stat = "bin", colour = "red")+ ggtitle("Number of paints pr year")+labs(x="Time",y="Number of painting")
plot(p)
# Q4

library("readr")
library("dplyr")
library("lubridate")
# Reading the data again

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# Creating dataframe only with paintings

df1=subset(df,Classification=="Painting")
# Creating a dataframe of the stock of paintings grouped by what department the painting belongs to:

df.4=df1%>%
  group_by(Department)%>%
  summarise(numberofpaints = n())
# There are 4 departments, thus 4 observations in the dataframe
# Q5
# Plotting the dataframe from Q4 showing stock of paintings for each department:

p = ggplot(df.4, aes(x = Department, y = numberofpaints))
p + geom_histogram(stat="identity")
# Painting&sculpture has the most.
# Q6

library("readr")
library("dplyr")
library("lubridate")
# Reading the dataframe once again

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# Making a dataframe only with paintings

df1=subset(df,Classification=="Painting")
# Counting the number of paintings by each artist in the dataset.
# At the same time we list the 10 painters with highest number of paintings:

df.6=df1%>%
  group_by(Artist)%>%
  summarise(numberofpaints = n())
top_n(df.6,10)
# Q7

library("readr")
library("dplyr")
library("lubridate")
library("stringr")
library("ggplot2")
library("maps")
# Reading the data again

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# Keeping only the paintings

df1=subset(df,Classification=="Painting")
# Making a new dataframe grouped by ArtistBio (the birth place of each painter)

df.7=df1%>%
  group_by(ArtistBio)%>%
  summarise(numberofpaints = n())
# Cleaning

df.7$ArtistBio = gsub("\(|\),+", "", df.7$ArtistBio) 
df.7$ArtistBio = str_extract(df.7$ArtistBio, "[A-z]+")
# We merge a dataset which can translate nationalities into countries (the dataset is in excel, so you need the file te redo the solution)

df.nation=read.table("Country_Nationality_2.csv",sep=";", header=TRUE)
df.nation$ArtistBio=df.nation$adjective
# Merging our dataframe with the dataframe translating nationality into country:

df.7b=inner_join(df.7, df.nation)
# Grouping the paintings by country

df.7c=df.7b%>%
  group_by(country)%>%
  summarise(numberofpaints = n())
# Map

df_world=map_data("world")
df_world$country=df_world$region
# Merging with the world map

df.7c=full_join(df.7c, df_world)
# Making a map

p = ggplot(df.7c, aes(x = long, y = lat, group = group, fill = numberofpaints)) 
p = p + geom_polygon() + expand_limits(x=df.7c$long, y=df.7c$lat)
plot(p)
# Q8
# Copying the dataframe df1

df_8=df1
# Extracting the high and length

df_8$hoejde=str_extract(df_8$Dimensions, "([0-9]+.[0-9]\* x+ [0-9]+.[0-9]\* cm)")
df_8$lenght=str_extract(df_8$hoejde, "x [0-9]+.[0-9]\* cm")
df_8$lenght=gsub("x", "", df_8$lenght)
df_8$lenght=gsub("cm", "", df_8$lenght)
df_8$hoejde=gsub("x [0-9]+.[0-9]\* cm", "", df_8$hoejde)
# Both lenght and high needs to be numeric variables

class(df_8$lenght)="numeric"
class(df_8$hoejde)="numeric"
# Calculating the area by using the length and high

df_8$area = df_8$lenght*df_8$hoejde
# Creating a data frame of the five largest and five smallest paintings in MOMA's collection:
# arranging the dataframe after area

df8b=arrange(df_8, desc(area))
# omitting the observations with missing information

df8b=na.omit(df8b)
# Making a new dataframe with the five smallest and five largest paintings:

df8c=df8b[c(1:5,2140:2144),]
df8c$area

**Comment by sebastianbarfort** [comment]
Large parts of the assignment is pretty good. 

Some smaller details:
- Think about using lines instead of bars for time series data. 
- Also, when using bars remember to use `fill` instead of `colour`. 
- Try to write your code so you don't have to re-read the data again and again

**APPROVED**
