### ISSUE TITLE
Group 26: Assignment 1

### ISSUE THREAD

**Issue by kasperwerlauff** [sebastianbarfort/sds#14]
library("readr")
library("stringr")
library("lubridate")
library("dplyr")
library("ggplot2")
library("maps")
# Question 1 -----------------
# Import data:

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# In the following we assume that the term 'paintings' include every artwork at MOMA. In doing so, we
# don't filter out any data to begin with.
# We want to compute the stock of paintings for each month and year in the dataset. Therefore we need to
# sum up every painting acquired in each unique month and year of the dataset. We do this by manipulating
# the variable 'DateAcquired'.
# First we make a variable 'DateAcq_ym' which only contains the year and month of acquiring.

df$DateAcq_ym = substr(df$DateAcquired,1,7)
# The following lines of code (line 25 to line 44) is only to make the x-axis in #Q2 nicer. The code
# manipulates the 'DateAcq_ym' variable, so it can be converted to a date format again.

df$DateAcq_ym  = gsub("-","",df$DateAcq_ym) #removes '-' and replaces with 'nothing'.

df$DateAcq_ym = as.numeric(df$DateAcq_ym) #change the format to numeric

class(df$DateAcq_ym) #checks if the format is numeric

df = mutate(df, DateAcq_ym = DateAcq_ym + 0.28) #We add 0.28 so we don't run into trouble when formatting
# into dates further down the code. Eg. if we added 0.31 and making into dates would give us NA's for the
# months where there is not 31 days in them. For example april or february...

df$DateAcq_ym = as.character(df$DateAcq_ym) #change the format to character

df$DateAcq_ym  = gsub("\.","",df$DateAcq_ym) #removes the '.' with 'nothing'.

df$DateAcq_ym = as.Date(df$DateAcq_ym, format = "%Y%m%d") #changes the format to dates. Note the format
# command clarifies how the data should be read. The command is case sensitive. Eg. when typing 'y' it will
# only read a year as two characters, but 'Y' says that the year is four characters long.

class(df$DateAcq_ym) #checks if the format is date
# A new dataframe is created with the accummulated sum of paintings for each month

df_n = count(df, DateAcq_ym)
df_n$cumdate = cumsum(df_n$n)
# We want to get rid of NA's, eg. paintings that do not have an exact date of acquiring.

df_n = na.omit(df_n)
# This reduces our stock of paintings from 123.919 to 119.485
# The cumulutative increase (6 last rows) in the stock is shown in the console window.

tail(df_n)
# Question 2 ----------------------------
# The ggplot is created. We use geom_area because it illustrates cumulative data in a good way. We
# could also use geom_bar, however geom_area is a easier way to answer question #3.

p = ggplot(data = df_n, aes(x = DateAcq_ym, y = cumdate)) # data & aesthetics
p = p + geom_area(colour = "black", fill = "red") #colouring the line and filling the graph
p = p + labs(y="Stock of paintings at MOMA", x="Date (1929-2015)") #Axis labels
p = p + theme_minimal()#adding the minimal theme to the graph
# p = p + theme(axis.text.x = element_text(angle=90))

p #printing the graph
# Question 3 ----------------------------
# Before we can make the graph, we need to manipulate the 'CuratorApproved' variable, so that we can use
# it in our graph.
# First step is to make it into a dummy variable that takes the value = 1 when the painting is Curator
# approved and the value = 0 when it is not or when the 'CuratorApproved' variable is missing.

df$Y = as.numeric(df$CuratorApproved == "Y") #This makes a new variable 'Y' with value = 1 when 
# 'CuratorApproved' is equal to "Y" and with value = 0 when 'CuratorApproved' is not equal to "Y"
# Now we use the tapply function to sum the 'Y' variable for each unique month and year (eg. "1929-11")
# which is almost the same procedure as in question #1 when we created a dataframe with the accummulated
# sum of paintings for each month

v_t = tapply(df$Y, df$DateAcq_ym, FUN=sum) #the 'tapply' function is generating the new data into a vector
# 'v_t'which contains 732 rows (one for each unique monht and year). Each entry in 'v_t' contains the
# number of curator approved paintings for that specific month and year.
# We add the vector to the dataframe "df_n" and give it the name 'Yn'. Then we make the cumulative
# variable 'cumY'.

df_n$Yn = v_t
df_n$cumY = cumsum(df_n$Yn)
# We are now able to make the required plot.

p = ggplot(data = df_n, aes(x = DateAcq_ym, y = cumdate))# data & aesthetics
p = p + geom_area(colour="black", fill = "red") #colouring the line and filling graph
p = p + geom_area(aes(x = DateAcq_ym, y = cumY, colour ="CuratorApproved"), fill = "blue") #adding another area which shows
# the stock of approved paintings over time

p = p + labs(y="Stock of paintings at MOMA", x="Date (1929-2015)") #Axis labels
p = p + theme_minimal() #adding the minimal theme to the graph
p #printing the graph
# At the end of 2015-06 MOMA has a stock of 56.278 Curator approved paintings -> more than half of the
# paintings is not approved (not taking missing variables into account).

tail(df_n) 
# Question 4 ----------------------------
# A count function is used to sum up the final stock of paintings in each department.
# A new dataframe is created with the result.

df_q4 = count(df,Department)

head(df_q4, 9) # shows the 9 different departments with the stock of paintings listed (by 2015-06)
# Question 5 ----------------------------
# A graph showing the stock of painting for each department is created

p = ggplot(df_q4, aes(x = reorder(Department, n), y = n)) #reorders so the Department with is
# sorted by number of paintings.

p = p + geom_bar(stat = "identity") + coord_flip() #adding the geom_bar and flips the horizontal and
# vertical axis.

p = p + labs(x="Department", y="Total stock")
p = p + theme_minimal() #adding the minimal theme to the graph
p
# The department with the greatest increase in stock of paintings has been the department named
# "Prints & Illustrated Books", stock = 58.268 by 2015-06
# Question 6 ----------------------------
# A count function is used to count the number of paintings for each artist. We deliberately choose to
# include unknown artist and missing artist.

df_q6 <- count(df,Artist)
# The data is arranged in a descending order with the artist with the most paintings at MOMA.

df_q6 <- arrange(df_q6,desc(n))
# The top 10 artists in stock is presented

head(df_q6,10)
# The top three artist:
#1             EugÃ¨ne Atget  5050
#2          Louise Bourgeois  3224
#3  Ludwig Mies van der Rohe  2497
# Question 7 ----------------------------
# From the 'ArtistBio' variable we are able to retrieve information about the nationality and the birth place
# of each artist. We want to make the graph according to their birth place.

df$ArtistBio = tolower(df$ArtistBio) # #make shure everything is in lowercase letters for 
# the following code.

df_q7 = select(df, Artist, ArtistBio)

df_q7 = na.omit(df_q7)

df_q7$nationality = str_extract(df_q7$ArtistBio, "[a-z]+")

df_q7$bp  = str_extract(df_q7$ArtistBio, "born [a-z]+")

df_q7$bp = gsub(pattern = "born ", replacement = "", df_q7$bp)

df_cnt = count(df_q7, bp)
# We haven't succeeded in completing #Q7 because of difficulty matching the countries with their nationality.
# Here are the steps we would have done though:
#1: In each entry where we get an NA for the variable 'bp' (birth place), we would use the created
# nationality variable to determine the artist birth place. For example Walter Pichler have an NA for 'bp'
# but is listed as an austrian in the 'nationality' variable, so we would list the birth place of
# Walter Pichler as Austria.
#2: Hereafter we would merge the world_map dataset from map_data (package maps) with df_q7 by country.
# This would give us the longi- and latitudes of each country and we would be able to make the desired plot.
# The code would probably look something like this:
# p = ggplot(df.merge, aes(x = long, y = lat, group = group, fill = bp))
# p + geom_polygon() +

  #expand_limits(x = df.merge$long, y = df.merge$lat)
# Question 8 ----------------------------
# Unlike q1-q7 we will now consider paintings as things in a frame, i.e things in a rectangular format.
# We therefore use the variable 'Classification' to decide whether an artwork is a painting.

table(df$Classification)
# We find that the following 7 classifications looks like matches to our 'painting definition':
# "A&D Architectural Drawing", "A&D Photograph", "Collage", "Drawing", "Painting", "Print", "Work on Paper"
# However, we can't be completely sure, that the selected paintings have rectangular shapes, which will
# be important when choosing the proper area function. We will assume, that the selected classifications
# have a rectangular shape.

condition = c("A&D Architectural Drawing", "A&D Photograph", "Collage", "Drawing", "Painting", 
              "Print", "Work on Paper") #we make a vector of conditions.

df_q8  = df %>% #Make a dataset 'df_q8' equal to df, then do
  select(Classification, Dimensions) %>% #select two variables 'Classification' and 'Dimensions' from
  #'df' and put it into 'df_q8', then do
  filter(Classification %in% condition) #filter the data in 'df_q8' so that condition vector categories
# are equal to the categories in df_q8.

table(df_q8$Classification) #To check if the above three lines of code do the correct thing.

df_q8$Dimensions = tolower(df_q8$Dimensions) #make shure everything is in lowercase letters for 
# the following code.
# Vocabulary for the following code:
# '.' = The period . matches any single character.
# '?' = The preceding item is optional and will be matched at most once.
# '*' = The preceding item will be matched zero or more times.
# '+' = The preceding item will be matched one or more times.
# (http://stat.ethz.ch/R-manual/R-patched/library/base/html/regex.html)

df_q8$Dimen = str_extract(df_q8$Dimensions, "\([0-9].*cm?") #Extract from ([0-9] and every other 
# character until you meet 'cm' for the first time. Extract this to a new variable 'Dimen'.

df_q8$Dimen = gsub(pattern = "\(", replacement = "", df_q8$Dimen) #search for '(' and replace with 'nothing'

df_q8$Dimen = gsub(pattern = "cm", replacement = "", df_q8$Dimen) #search for 'cm' and replace with 'nothing'

df_q8$length = str_extract(df_q8$Dimen, "[0-9]+.[0-9]*") #Make a new variable 'length' to the dataset
# which contains every digit until the first 'x'.

df_q8$width = str_extract(df_q8$Dimen, "x.[0-9]+.[0-9]*") #Make a new variable 'width' to the dataset
# which contains every digit after the first 'x'.

df_q8$width = gsub(pattern = "x ", replacement  = "", df_q8$width) #search for 'x ' and replace with 'nothing'

df_q8$width = as.numeric(df_q8$width) #make the variable into a numeric format.
df_q8$length  = as.numeric(df_q8$length) #make the variable into a numeric format. 
# The area equation is as follows: length x width. So:

df_q8  = mutate(df_q8, area = length \* width) #make a new area variable.

df_q8 = na.omit(df_q8) #Omit NA's.

df_area = select(df_q8, area) #make a new dataset with the area variable.

df_area = arrange(df_area, desc(area)) #arrange data in a descending order.

head(df_area)

df_area2 = df_area[c(1:5, 36870:36874),] #Make a new dataset with the first and the last five rows of
# the area dataset.

df_area2 #print the new dataset in the console window
# So the largest painting has an area equal to 798.972,24 cm^2, while the smallest painting
# have an area equal to 0,30 cm^2.

**Comment by sebastianbarfort** [comment]
Generally a pretty good assignment. 

Nice use of `ggplot` functions such as `geom_area` and `coord_flip`. 

Ok with question 7. Check my solution. 

**APPROVED**
