### ISSUE TITLE
Group 17: Assignment 1

### ISSUE THREAD

**Issue by michalmroz** [sebastianbarfort/sds#16]
## Assignment 1
# Reading necessary libraries for the assignment

library("dplyr")
library("ggplot2")
library("readr")
library("zoo")
library("lubridate")
library("stringr")
# loading the dataset

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
tbl <- tbl_df(df)
# Creating a new dataframe and subsetting data so we only analyse paintings

ptbl <- subset(tbl, Classification=="Painting") 
# Question 1 ---------------
# Dataframe with the number of new paintings each month

a <- ptbl %>%
  filter(!is.na(DateAcquired)) %>% # removing missing values
  mutate(MonthAcquired=as.yearmon(DateAcquired)) %>% #attaching a YearMon variable
  group_by(MonthAcquired) %>% # grouping by the YearMon variable
  summarise(NumberOfArtworks=n()) # summing the number of paintings in a month
# Dataframe with the cummulative of paintings in a month

NumberOfArtworks <- a %>%
  mutate(NumberTotal=cumsum(NumberOfArtworks)) %>% #cummulative sum
  select(MonthAcquired,NumberTotal) #removing the middle column
# Question 2 ---------------
# Drawing a plot with the number of paintings over time

ex2 = ggplot(data=NumberOfArtworks, aes(x=as.numeric(MonthAcquired), y=NumberTotal)) # setting up the data for the plot
ex2 = ex2 + geom_step(size=1, colour="red" ) ## adding a step plot
# We think step plot is appropriate because the number of paintings increases at a given point in time and stays this way until the next increase

ex2 = ex2 + labs(title="Number of paintings in MOMA over time", x="Time", y="Number of paintings")
ex2 # plotting
# Question 3 ---------------
# Creating a data frame with the number of paintings acquired in a month

c <- ptbl %>%
  filter(!is.na(DateAcquired)) %>% # removing missing values
  mutate(MonthAcquired=as.yearmon(DateAcquired)) %>% #attaching a YearMon variable
  group_by(MonthAcquired,CuratorApproved) %>% # grouping by the YearMon and CuratorApproved variables
  summarise(NumberOfArtworks=n()) # summing the number of paintings in a month
# Creating a data frame with the cummulative sum of acquired paintings (=the stock of paintings at a given point in time)

d <- c %>% 
  group_by(CuratorApproved) %>%
  mutate(total=cumsum(NumberOfArtworks))
# Plotting a step plot

ex3 = ggplot(data=d, aes(x=as.numeric(MonthAcquired), y=total, colour=CuratorApproved)) #setting up data for the plot
ex3 = ex3 + geom_step(size=1) #plotting the step plot
ex3 = ex3 + labs(title="Number of paintings in MOMA over time", x="Time", y="Number of paintings")
ex3 # plotting
# Summarising the number of curator approved and non-approved paintings (to check with the data in the plot)

ptbl %>% 
  group_by(CuratorApproved) %>%
  summarise(a=n())
# Question 4 ---------------
# Creating a dataframe summarising the number of paintings by department

ByDepartment <- ptbl %>%
  filter(!is.na(Department)) %>% ## filtering missing values - no values removed
  group_by(Department) %>% # grouping by department
  summarise(Stock=n()) # summarising
# Question 5 ---------------
# Creating a plot with the number of paintings by department

ex5 = ggplot(data=ByDepartment, aes(x=reorder(Department,Stock),y=Stock)) #setting up data for the plot
ex5 = ex5 + geom_bar(stat="identity")+coord_flip() #plotting and flipping the coordinates of the plot
ex5 = ex5 + labs(title="Artworks by department", x="Stock of artworks", y="Department") #adjusting the visuals of the plot
ex5 #plotting
# Question 6 ---------------
# Creating a dataframe with the number of paintings by artist

ByArtist <- ptbl %>%
  filter(!is.na(Artist)) %>% #any NAs in the dataset?
  filter(Artist!="") %>% #missing values as strings
  group_by(Artist) %>% #grouping by the artist variable
  summarise(Number=n()) %>% #summing up by the number of paintings
  arrange(-Number)

head(ByArtist,10) #top 10 painters
# Question 7 ---------------
# Creatng a dataframe only with the ArtistBio and Artist name

df = ptbl %>%
  select(ArtistBio, Artist) 
# Cleaning the data
# Finds the first word starting with capital Letter that does not have a "born" somewhere in the text after it. In the examples above, it will find Austrian and Switzerland.

df$ArtistBirth=str_extract(df$ArtistBio, "[A-Z][a-z]+(?!.+born)")
# Find Words starting with capital letter. Word is only found if it is followed by an arbitrary number of random characters and the word "born" followed by blank space and 4 digits.

df$ArtistBirtha=str_extract(df$ArtistBio,"[A-Z][a-z]+(?=.+born\s\d{4})")
# Replacing all the NA's with blanks

df[is.na(df)] <- "" 
# Creating a new variable where ArtistBirth and ArtistBirtha is mergerd

ArtistBirth <- df %>%
  mutate(birthplace=paste(ArtistBirth,ArtistBirtha, sep=""))
# Summing up the number of paintings for the country (data not entirely clean yet)

countries <- ArtistBirth %>%
  group_by(birthplace) %>%
  summarise(a=n()) %>%
  arrange(-a)
# Creating a dataframe with paintings from all countries except American, French, German and Spanish

birtha <- ArtistBirth %>%
  filter(birthplace!="American" & birthplace!="French") %>%
  filter(birthplace!="German" & birthplace!="Spanish") %>%
  arrange(birthplace)

library(plyr)
# Recoding all the names into country names

ArtistBirth$birthplace <- revalue(ArtistBirth$birthplace, 
                                  c("American"="USA", "French"="France", "German"="Germany",
                                    "Spanish"="Spain", "British"="UK", "Italian"="Italy",
                                    "Japanese"="Japan","Belgian"="Belgium","Dutch"="Netherlands",
                                    "Mexican"="Mexico","Russian"="Russia","Swiss"="Switzerland",
                                    "Argentine"="Argentina","Polish"="Poland","Austrian"="Austria",
                                    "Brazilian"="Brazil","Canadian"="Canada","Cuban"="Cuba",
                                    "Australian"="Australia","Uruguayan"="Uruguay","Chilean"="Chile",
                                    "Danish"="Denmark","Colombian"="Colombia","Czech"="Czech Republic",
                                    "Indian"="India","Israeli"="Israel","Peruvian"="Peru",
                                    "Great"="UK","Haitian"="Haiti","Venezuelan"="Venezuela",
                                    "Croatian"="Croatia","England"="UK","Hungarian"="Hungary",
                                    "Romanian"="Romania","South"="South Africa","Icelandic"="Iceland",
                                    "Irish"="Ireland","Korean"="South Korea","Korea"="South Korea",
                                    "The"="Philippines","Turkish"="Turkey","Yugoslav"="Yugoslavia",
                                    "Zimbabwean"="Zimbabwe","Belorussia"="Belarus","Ukrainian"="Ukraine",
                                    "Tunis"="Tunisia","Tanzanian"="Tanzania","Sudanese"="Sudan",
                                    "Norwegian"="Norway","Bolivian"="Bolivia","Congolese"="Congo",
                                    "Ghanaian"="Ghana","Guatemalan"="Guatemala","Guyanese"="Guyana",
                                    "Iranian"="Iran","Moroccan"="Morocco","Nicaraguan"="Nicaragua",
                                    "Czechoslovakia"="Czech Republic", "Beirut"="Lebanon", "Scotland"="UK",
                                    "Swedish"="Sweden"))

detach(package:plyr)
# Creating a final dataframe with the stock of paintings by the country of artist

BirthplaceSummary <- ArtistBirth %>%
  group_by(birthplace) %>%
  filter(birthplace!="") %>% #removing blank values
  filter(birthplace!="Czechoslovakia") %>%
  filter(birthplace!="Yugoslavia") %>% ##fitering out values that cannot be unanimously assigned to a country
  summarise(number=n())

library("rworldmap")
# Joining the dataframe with the world map

sPDF <- joinCountryData2Map(BirthplaceSummary, joinCode="NAME",
                            nameJoinColumn = "birthplace", verbose=TRUE)
# Plotting the map with the stock of paintings by country

ex7 <- mapCountryData(sPDF,nameColumnToPlot="number",colourPalette="white2Black",
                            addLegend=FALSE, mapTitle="Stock of paintings by country")
# Adding a legend to the map

do.call(addMapLegend, c(ex7
                        , legendLabels=("all")
                        ))
# Question 8 ---------------
# Selecting the columns with painting name and dimensions

df8 = ptbl %>%
  select(-(ArtistBio:Medium), -(CreditLine:URL)) 
# Extracting dimensions

df8$Dimensions2=gsub("Frame._","",df8$Dimensions)
df8$Dimensions2=gsub("\)._", "", gsub("._\(", "", gsub(".\cm_", "",df8$Dimensions2)))
subsetting <- grepl("x", df8$Dimensions2)
df8 <- df8[subsetting,]
df8 <- df8[-1994,]
df8 <- df8[-712,]
df8$width <- as.numeric(word(as.character(df8$Dimensions2),1))
df8$length <- as.numeric(word(as.character(df8$Dimensions2),3))
# Calculating the areas and arranging them

df9 <- df8 %>% 
  mutate(area=length*width) %>% 
  filter(!is.na(area)) %>%
  arrange(area)
# Creatig a dataframe with five smallest paintings

fivesmallest<-head(df9,5)  
# Creating a dataframe with five largest paintings

fivelargest<- df9 %>% 
  arrange(-area) %>%
  head(5)

**Comment by sebastianbarfort** [comment]
Generally a very good assignment. 

I think you use the `dplyr` verbs very well. 

I would recommend using `ggplot2` in question 7 as well. Check my solution. 

**APPROVED**
