### ISSUE TITLE
Group 10: Assignment 1

### ISSUE THREAD

**Issue by annakollerup** [sebastianbarfort/sds#20]
library(readr)
library(dplyr)
library(ggplot2)
library(zoo)
library(stringr)
library(rex)

library(data.table)
library(rvest)
library(XML)
library(maps)
library(countrycode)
library(mapdata)

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
df2=df
# Q:1. Create a new dateframe of the stock of paintings at MOMA for each month of the year.

```
  #Note: We decided to create data for paintings acuired for each year. 
         #By Stock it could also have been understod as adding year by year if
         #we assume that paintings do not depreciate (at least not to an full extend.), 
         #so that new paintings enter into the already existing stock quantity.
         #But more easy to see year by year change with accuired by year. 
```

  df2<-filter(df2, df2$Classification == "Painting") %>% #Create new dataset filtered by Painting
  mutate(month = as.character(format(DateAcquired, "%m")), #creates new variable to month accuired
         year = as.character(format(DateAcquired, "%Y")))  #creates new variable for year accuired

  q1<-group_by(df2, year) %>% #groups paintings by year acuired
  tally(sort=FALSE)# counts paintings accuired for the given year
  names(q1)=c("year","stock")
  q1 # look at dataset before na omit
  q1<-na.omit(q1) #omits stock for year=na.
# Q:2. Use ggplot2 and your new data frame to plot the the stock of paintings on the y-axis and the date on the x-axis

  p <- ggplot(q1, aes(x = year, y = stock)) #choose x,y
  p <- p + geom_bar(stat = "identity", fill = "red", color = "red") + #choose bar plot and color, identity: bars represents values
    labs(title = "Number of paintings acuired per year", y = "Number of paintings", x = "Year") + #create labels
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) #adjust legend vertical
  p #call plot
# Q:3. Create the same plot but this time the color should reflect the stock of paintings for curator approved and non-curator approved paintings, respectively

  q3 <- group_by(df2, CuratorApproved, year) %>% tally(sort=FALSE)
  q3 <- na.omit(q3)

  p2 <- ggplot(q3, aes(x = year, y = n, fill=CuratorApproved)) #choose x,y and fill by approved/nnot approved
  p2 <- p2 + geom_bar(stat = "identity")+ labs(title = "Number of paintings acuired per year", y = "Number of paintings", x = "Year") + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
  p2 <- p2 + scale_fill_discrete(labels=c("No","Yes")) #Label text 
  #p2 <- p2 + scale_fill_brewer(palette = "Set1") #Two scale fills does not work, therefore Miami Vice Colors.  
  p2
# Q:4. Create a new dataframe of the stock of paintings grouped by what department the painting belongs to.

```
#When working with paintings only the main contributer to accumulating paintings is Painting and Sculpture department. 
#Very few observations for other Departments. 
```

  q4 <- group_by(df2, Department, year) %>% tally(sort=FALSE)  
  q4 <-na.omit(q4)
# Q:5. Plot this data frame using ggplot2. Which department  has had the highest increase in their stock of paintings?

  p3 <- ggplot(q4, aes(x = year, y = n)) +  #choose x,y
    geom_histogram(stat = "identity") + 
    labs(title="Stock of Paintings at MOMA Departments per Year", y="Stock of Paintings") + # title + y-axis 
    facet_wrap(~ Department, scales="free_y") + #create facet wrap and set y-axis "free" - should be used with cuation - can be missleading
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) #vertical axix labels. 
  p3
# Q:6. Write a piece of code that counts the number of paintings by each artist in the dataset.

  #List the 10 painters with the highest number of paintings in MOMA's collection.

  q6 <- group_by(df2, Artist) %>% #group by artist.
    tally(sort=TRUE)  #count number of paintings and sort by decending.
  q6[1:10,] #see if na-observations is in top 10.
# Q:7. The variable ArtistBio lists the birth place of each painter.

  #Use this information to create a world map where each country 
  #is colored according to the stock of paintings in MOMA's collection.

  #The variable Artistbio contains strings that need to be seperated-> 3 cases (maybe more). 
  #There is unfortuntaly not clear pattern for how 
  #ArtistBio is noted -> some manual checks has to be done. 
  #For Paintings with more than one artist we only choose one. 

  q7<-data.frame(df2$ArtistBio) 
  names(q7)=c("ArtistBio")

q7<-mutate(q7, b1=str_extract((str_extract(ArtistBio, "born._")),"[A-Z]._[a-z]")) #Country following born

```
q7$b1<-gsub("\\(.*","",q7$b1) #some elements still has text after country, eg. "(now Latvia" -> remove text and parenthesis.
q7$b1<-gsub("[0-9]","",q7$b1) #some elements still has birthyear after country, eg. "1948)" -> remove numbers and parenthesis.
q7$b1<-gsub("\\..*","",q7$b1) #some elements still has text after a '.' -> remove text after '.'.
q7$b1<-gsub("\\,.*","",q7$b1) #some elements still has text after a ',' -> remove text after ','.
q7$b1<-gsub("\\)","",q7$b1) #some elements still has ')' -> remove text after ','.
q7$b1<-gsub("Netherlands","Holland",q7$b1) #replace The Netherlands with Holland.
```

q7<-mutate(q7, b2=gsub("\,._","",ArtistBio)) #Elements with only nationality
    q7$b2<-gsub("\(","",q7$b2)
    q7$b2<-gsub("\)","",q7$b2) #some elements still has ')' -> remove text after ','.
    q7$b2<-gsub("then._","",q7$b2) #some elements has text with 'then .*'
    q7$b2<-gsub("Argentine","Argentinian",q7$b2) #replace Argentine with Argentinian.
    q7$b2<-gsub("American","US",q7$b2) #American with US.
# Redundant
# q7<-mutate(q7, b3=str_extract(q7$ArtistBio,".\* born [0-9]")) #number following born

```
#  q7$b3<-gsub("\\,.*","",q7$b3) #remove text/numbers after ','
#  q7$b3<-gsub("\\(","",q7$b3) #remove '( ','
```
# Create new vector with with b1 and b2.

q7<-mutate(q7, b_place=ifelse(is.na(q7$b1),q7$b2,q7$b1)) #use if-else function to create new vector.
# Remove whitespace - see http://stackoverflow.com/questions/2261079/how-to-trim-leading-and-trailing-whitespace-in-r

trim <- function (x) gsub("^\s+|\s+$", "", x) #defines function for trimming
q7$b1<-trim(q7$b1)
q7$b2<-trim(q7$b2)
q7$b_place<-trim(q7$b_place)
# When mapping we have to have country and not nationality.
# We found weppage with country and nationality and scraped to create dataset.
# Note: We looked for Terms of Use for the site but could not find anything, only https://www.englishclub.com/esl-forums/ucp.php?mode=terms.
# As the scraping is fairly limited and do not compromise servers or any private information is gathered, we did not see a problem with this.
# Scrape page for nationalities and country.

nat1 <- html("https://www.englishclub.com/vocabulary/world-countries-nationality.htm") %>% #declare website for scraping
  html_nodes("td:nth-child(2)") %>%   #which html element on page
  html_text() %>% #text from element
  as.character() #output as character

nat2 <- html("https://www.englishclub.com/vocabulary/world-countries-nationality.htm") %>%
  html_nodes("td:nth-child(1)") %>%  
  html_text() %>% 
  as.character()

nat<-data.frame(nat1,nat2) #combine nat1,nat2
names(nat)<-c("nat","country") #rename
nat$country<-gsub("\(._\)","",nat$country) #remove elements within paranthesis 
nat$country<-gsub("\,._","",nat$country) # remove text after ,
nat$nat<-gsub("\(._\)","",nat$nat) #remove elements within paranthesis 
nat$nat<-gsub("\s or ._","",nat$nat) #remove 'or' and test after (.*) + white space infront 
nat$nat<-gsub("UK","British",nat$nat) #replace UK or British with British.
nat$country<-gsub("Britain","United Kingdom",nat$country) #replace Britain with United Kingdom.
Israel<-c("Israeli","Israel") #create entry for Israel
nat<-rbind(nat,Israel) #add Isrel to nat
nat<-nat[-112,] #Drop Dutch - Netherlands - otherwise creates dublets when joining - Hazard to delete element by row number!
nat<-nat[-24,] #Drop dublet of british - 
nat$nat<-trim(nat$nat)
nat$country<-trim(nat$country)
# Join q7 and nat

q7.1 <- left_join(q7, nat,by=c("b_place"="nat")) #join by b_place and nationality
# place b1 into country

q7.1$country <-ifelse(is.na(q7.1$country),q7.1$b1,q7.1$country)
# Combine Scotland,and Great Britain into United Kingdom

q7.1$country<-ifelse(q7.1$country=="Scotland","United Kingdom",q7.1$country)
q7.1$country<-gsub("Great .*","United Kingdom",q7.1$country)
q7.1$country<-gsub("American","United States",q7.1$country) #Still there for some observations remove agin
# Rename Belorussia

q7.1$country<-gsub("Belorussia","Belarus",q7.1$country)
# see number of na's

which(is.na(q7.1$country))
# inspect na's

q7.1$country<-ifelse(q7.1$b_place=="Croatian","Croatia",q7.1$country)
# Problems with countrynames and ISO's -> change names once agin

q7.1$country<-gsub("United States of America","United States",q7.1$country) #could have been done before
q7.1$country<-gsub("Russia","Russian Federation",q7.1$country) 
q7.1$country<-gsub("England","United Kingdom",q7.1$country) 
q7.1$country<-gsub("Bolivia","Bolivia, Plurinational State of",q7.1$country) 
q7.1$country<-gsub("Holland","Netherlands",q7.1$country) 
q7.1$country<-gsub("Iran","Iran, Islamic Republic of",q7.1$country) 
q7.1$country<-gsub("The Philipines","Philippines",q7.1$country) 
q7.1$country<-gsub("Tunis","Tunisia",q7.1$country) 
q7.1$country<-gsub("Tanzania","Tanzania, United Republic of",q7.1$country) 
q7.1$country<-gsub("Venezuela","Venezuela, Bolivarian Republic of",q7.1$country) 
q7.1$country<-gsub("Beirut","Lebanon",q7.1$country) 

q7.2<-group_by(q7.1, country) %>% tally(sort=FALSE)
names(q7.2)<-c("country","paintings")

world_data<-countrycode_data #get dataset with ISO codes
q7.3<-left_join(q7.2,world_data,by=c("country"="country.name")) #merge after manuel check of names

world = map_data("world") #get geo coordinates
world$iso2c = countrycode(world$region, origin = "country.name", destination = "iso2c") #get iso2 into world coordinates

q7.4 <- full_join(q7.3, world,by="iso2c") #merge countries with paintings and countries without.

p = ggplot(q7.4, aes(x = long, y = lat, group = group, title='Paintings at MOMA by Birthplace of Artist')) +
  geom_polygon(aes(fill = paintings)) +
  expand_limits() +
  theme_minimal()
p 
# Q:8. The Dimensions variable lists the dimensions of each painting. Use your data manipulation skills to calculate the area of each painting (in cm's).
# Create a data frame of the five largest and five smallest paintings in MOMA's collection.

q8 = df2

q8$Dimensions <- sub("\)._", "", sub("._\(", "", q8$Dimensions)) #Remove unwanted parenthesis and text

q8$x <- gsub( " ['x'].*", "", q8$Dimensions ) #get x

q8$y <- gsub(".*['x']", "", q8$Dimensions) #get y
q8$y <- gsub("['cm']", "", q8$y) #remove cm

q8$x=as.numeric(q8$x) #change to numeric for calculations
is.numeric(q8$x) #test
q8$y=as.numeric(q8$y)
is.numeric(q8$y)
q8$xy=q8$x*q8$y

q8 <- arrange(q8, desc(xy)) #sort xy column by descending
head(q8,5) #show head
tail(na.omit(q8),5) #show tail - na.omit

**Comment by sebastianbarfort** [comment]
Good job. 

I think you might want to consider using lines instead bars/histograms for plotting time series data. 

Also, I think you might want to use `dplyr` a little bit more for doing data manipulation. I find that it makes my code easier to read. 

Nice use of web scraping using `rvest` (although `html` is now `read_html`). 

**APPROVED**
