### ISSUE TITLE
Group 12: Assignment 1

### ISSUE THREAD

**Issue by madjazz** [sebastianbarfort/sds#23]
# Assignment 1
## Read data into working directory

library("readr")

setwd("~/Documents/Universität/Københavns Universitet/Security Risk Management/3. Semester/Social Data Science/Assignment 1")
df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# Question 1: Create a new dataframe of the stock of paintings at MOMA for each month in the year.

library(zoo)
library(plyr)
## New Dataframe

df$DateAcquired <- as.yearmon(df$DateAcquired)
stock_my <- count(na.omit(df$DateAcquired))
## Binwidth

h = (max(as.numeric(stock_my$x)) - min(as.numeric(stock_my$x)) / sqrt(length(stock_my$x)))
## Plot

library(ggplot2)
library(scales)  
ggplot(stock_my, aes(x = as.Date(x))) + 
  geom_bar(color = "red", binwidth = h) + 
  scale_x_date(labels = date_format("%Y"), breaks = "10 years", limits = c(min(as.Date(stock_my$x)), max(as.Date(stock_my$x)))) +
  labs(title = "MOMA Stock of Paintings 1929 - 2015", x = "Year", y = "Stock of Paintings") +
  theme(plot.title = element_text(lineheight=.8, face="bold"))
# Question 2: Create the same plot but this time the color should reflect the stock of paintings for curator approved and non-curator approved paintings, respectively
## New dataframe

stock_cu <- df[, c(11, 12)]
stock_cu <- count(stock_cu)
## Plot

ggplot(stock_cu, aes(x = as.Date(DateAcquired), fill = CuratorApproved)) + 
  geom_bar(color = "red", binwidth = h, position = "dodge") + 
  scale_x_date(labels = date_format("%Y"), breaks = "10 years", limits = c(min(as.Date(stock_my$x)), max(as.Date(stock_my$x)))) +
  scale_fill_manual(values=c("red", "green")) +
  labs(title = "Curator Approval MOMA Stock of Paintings 1929 - 2015", x = "Year", y = "Stock of Paintings") +
  theme(plot.title = element_text(lineheight=.8, face="bold")) +
  guides(fill=guide_legend(title="Curator Approval"))
# Question 4: Create a new dataframe of the stock of paintings grouped by what department the painting belongs to
## New dataframe

stock_dp <- df[, c(10, 11)]
stock_dp <- count(stock_dp)
# Question 5: Plot this data frame using ggplot2

ggplot(stock_dp, aes(x = as.Date(DateAcquired))) + 
  geom_freqpoly(binwidth = h, aes(colour = Department)) + 
  scale_x_date(labels = date_format("%Y"), breaks = "10 years", limits = c(min(as.Date(stock_my$x)), max(as.Date(stock_my$x)))) +
  scale_colour_brewer(palette="Set1") +  
  labs(title = "MOMA Stock of Paintings by Department 1929 - 2015", x = "Year", y = "Stock of Paintings") +
  theme(plot.title = element_text(lineheight=.8, face="bold")) +
  guides(colour = guide_legend(override.aes = list(size=10)))
# Which department has had the highest increase in their stock of paintings?

  # Painting & Sculpture
# Question 6: Write a piece of code that counts the number of paintings by each artist in the dataset. List the 10 painters with the highest number of paintings in MOMA’s collection.
## New dataframe

count_ar <- count(df$Artist)
count_ar <- count_ar[-1, ]
## Order dataframe

count_ar <- count_ar[order(-as.numeric(count_ar$freq), decreasing = FALSE),]
## List the 10 painters with the highest number of paintings in MOMA’s collection.

top_10 <- head(count_ar, n = 10)
# Question 7: The variable ArtistBio lists the birth place of each painter. Use this information to create a world map where each country is colored according to the stock of paintings in MOMA’s collection.

library(dplyr)
## filter strings that do not include "born"

test <- filter(df, !grepl("born", ArtistBio)) 
test <- gsub("[\(\)]", "", test$ArtistBio) 
test <- gsub("[\,]", "", test)
test <- gsub("[0-9]", "", test)
test <- gsub("[\-]", "", test)
test <- str_extract(test, "[A-Z][a-z]+[ \t\n\r\f\v]")
test <- na.omit(test)

test <- gsub("Algerian", "Algeria", test)
test <- gsub("American", "USA", test)
test <- gsub("established", "", test)
test <- gsub("Argentine", "Argentina", test)
test <- gsub("Australian", "Australia", test)
test <- gsub("Austrian", "Austria", test)
test <- gsub("Belgian", "Belgium", test)
test <- gsub("Bolivian", "Bolivia", test)
test <- gsub("Brazilian", "Brazil", test)
test <- gsub("British", "UK", test)
test <- gsub("Canadian", "Canada", test)
test <- gsub("Chilean", "Chile", test)
test <- gsub("Chinese", "China", test)
test <- gsub("Colombian", "Colombia", test)
test <- gsub("Costa", "Costa Rica", test)
test <- gsub("Croatian", "Croatia", test)
test <- gsub("Cuban", "Cuba", test)
test <- gsub("Czech", "Czech Republic", test)
test <- gsub("Danish", "Denmark", test)
test <- gsub("Dutch", "Netherlands", test)
test <- gsub("Ecuadorian", "Ecuador", test)
test <- gsub("English", "UK", test)
test <- gsub("Ethiopian", "Ethiopia", test)
test <- gsub("Finnish", "Finland", test)
test <- gsub("French", "France", test)
test <- gsub("Georgian", "Georgia", test)
test <- gsub("German", "Germany", test)
test <- gsub("Germanyy", "Germany", test)
test <- gsub("Greek", "Greece", test)
test <- gsub("Guatemalan", "Guatemala", test)
test <- gsub("Haitian", "Haiti", test)
test <- gsub("Hungarian", "Hungary", test)
test <- gsub("Icelandic", "Iceland", test)
test <- gsub("Indian", "India", test)
test <- gsub("Iranian", "Iran", test)
test <- gsub("Irish", "Ireland", test)
test <- gsub("Israeli", "Israel", test)
test <- gsub("Italian", "Italy", test)
test <- gsub("Jackson", "USA", test)
test <- gsub("Japanese", "Japan", test)
test <- gsub("Latvian", "Latvia", test)
test <- gsub("Lithuanian", "Lithuania", test)
test <- gsub("Malian", "Mali", test)
test <- gsub("Mexican", "Mexico", test)
test <- gsub("Moroccan", "Morocco", test)
test <- gsub("Namibian", "Namibia", test)
test <- gsub("Nicaraguan", "Nicaragua", test)
test <- gsub("Nigerian", "Nigeria", test)
test <- gsub("Norwegian", "Norway", test)
test <- gsub("Osaka", "Japan", test)
test <- gsub("Panamanian", "Panama", test)
test <- gsub("Peruvian", "Peru", test)
test <- gsub("Polish", "Poland", test)
test <- gsub("Portuguese", "Portugal", test)
test <- gsub("Romanian", "Romania", test)
test <- gsub("Russian", "Russia", test)
test <- gsub("Scottish", "Scotland", test)
test <- gsub("Sengalese", "Senegal", test)
test <- gsub("Slovak", "Slovakia", test)
test <- gsub("Slovenian", "Slovenia", test)
test <- gsub("South", "South Africa", test)
test <- gsub("Korean", "South Korea", test)
test <- gsub("Senegalese", "Senegal", test)
test <- gsub("Spanish", "Spain", test)
test <- gsub("Swedish", "Sweden", test)
test <- gsub("Swiss", "Switzerland", test)
test <- gsub("Tanzanian", "Tanzania", test)
test <- gsub("The", "Netherlands", test)
test <- gsub("Turkish", "Turkey", test)
test <- gsub("Ukrainian", "Ukraine", test)
test <- gsub("Uruguayan", "Uruguay", test)
test <- gsub("Venezuelan", "Venezuela", test)
test <- gsub("Yugoslav", "Serbia", test)
test <- gsub("Zagreb", "Croatia", test)
test <- gsub("Zimbabwean", "Zimbabwe", test)

detach("package:dplyr", unload=TRUE)

test <- count(test)
test <- test[-c(1, 41, 68),]
## filter strings that include "born"

tset <- str_extract(df$ArtistBio, "born[:space:][[a-zA-Z]+]*")
tset <- gsub("born", "", tset)
tset <- tset[tset != " "]
tset <- na.omit(tset)

tset <- gsub("America", "USA", tset)
tset <- gsub("Amsterdam", "Netherlands", tset)
tset <- gsub("Barcelona", "Spain", tset)
tset <- gsub("Belorussia", "Belarus", tset)
tset <- gsub("Britain", "UK", tset)
tset <- gsub("Constantinople", "Turkey", tset)
tset <- gsub("Bohemia", "Czech", tset)
tset <- gsub("Czech", "Czech Republic", tset)
tset <- gsub("Czech Republicoslovakia", "Czech Republic", tset)
tset <- gsub("England", "UK", tset)
tset <- gsub("German", "Germany", tset)
tset <- gsub("Germanyy", "Germany", tset)
tset <- gsub("Great", "UK", tset)
tset <- gsub("Hawaii", "USA", tset)
tset <- gsub("Holland", "Netherlands", tset)
tset <- gsub("Hong", "China", tset)
tset <- gsub("South", "South Africa", tset)
tset <- gsub("Korea", "South Korea", tset)
tset <- gsub("Moravia", "Czech Republic", tset)
tset <- gsub("New", "New Zealand", tset)
tset <- gsub("Lituania", "Lithuania", tset)
tset <- gsub("Pinar", "Cuba", tset)
tset <- gsub("Puerto", "Puerto Rico", tset)
tset <- gsub("Rumania", "Romania", tset)
tset <- gsub("Russian", "Russia", tset)
tset <- gsub("Scotland", "UK", tset)
tset <- gsub("Silesia", "Poland", tset)
tset <- gsub("the", "Netherlands", tset)
tset <- gsub("The", "Netherlands", tset)
tset <- gsub("NeNetherlandsrlands", "Netherlands", tset)
tset <- gsub("Transylvania", "Romania", tset)
tset <- gsub("Tunis", "Tunisia", tset)
tset <- gsub("Tunisiaia", "Tunisia", tset)
tset <- gsub("United", "USA", tset)
tset <- gsub("Wales", "UK", tset)
tset <- gsub("Yugoslavia", "Serbia", tset)

tset <- count(tset)
tset <- tset[-c(2, 5, 16, 17, 35, 69),]
## Generate Map Data

a1 <- rep(45, 410)
a2 <- rep(16, 118)
a3 <- rep(20, 383)
a4 <- rep(0, 8)
a5 <- rep(0, 19)
a6 <- rep(0, 338)
a7 <- rep(0, 6)
a8 <- rep(0, 4658)
a9 <- rep(0, 12)
a10 <- rep(353, 1093)
a11 <- rep(19, 146)
a12 <- rep(0, 10)
a13 <- rep(0, 11)
a14 <- rep(102, 1804)
a15 <- rep(979, 273)
a16 <- rep(0, 264)
a17 <- rep(0, 67)
b18 <- rep(2, 268)
b19 <- rep(0, 13)
b20 <- rep(1, 384)
b21 <- rep(0, 9)
b22 <- rep(0, 10)
b23 <- rep(1161, 321)
b24 <- rep(748, 164)
b25 <- rep(0, 65)
b26 <- rep(0, 147)
b27 <- rep(0, 8)
b28 <- rep(0, 100)
b29 <- rep(2, 467)
b30 <- rep(0, 10)
b31 <- rep(0, 146)
b32 <- rep(0, 221)
b33 <- rep(200, 1925)
b34 <- rep(0, 56)
b35 <- rep(386, 179)
b36 <- rep(0, 255)
b37 <- rep(0, 84)
c38 <- rep(0, 221)
c39 <- rep(0, 350)
c40 <- rep(380, 12276)
c41 <- rep(0, 94)
c42 <- rep(0, 87)
c43 <- rep(0, 36)
c44 <- rep(0, 324)
c45 <- rep(0, 291)
c46 <- rep(0, 17)
c47 <- rep(271, 2006)
c48 <- rep(56, 2712)
c49 <- rep(0, 9)
c50 <- rep(0, 26)
c51 <- rep(87, 623)
c52 <- rep(0, 35)
c53 <- rep(0, 11)
c54 <- rep(64, 133)
c55 <- rep(18, 374)
c56 <- rep(212, 305)
c57 <- rep(0, 10)
c58 <- rep(0, 100)
c59 <- rep(529, 240)
d60 <- rep(0, 681)
d61 <- rep(267, 298)
d62 <- rep(0, 56)
d63 <- rep(0, 10)
d64 <- rep(0, 112)
e65 <- rep(4, 347)
e66 <- rep(46, 253)
e67 <- rep(0, 74)
e68 <- rep(0, 67)
e69 <- rep(0, 192)
e70 <- rep(130, 198)
e71 <- rep(43, 302)
f72 <- rep(0, 149)
f73 <- rep(0, 63)
f74 <- rep(0, 268)
f75 <- rep(200, 571)
f76 <- rep(22023, 605)
f77 <- rep(0, 127)
f78 <- rep(0, 185)
f79 <- rep(0, 119)
g80 <- rep(0, 271)
g81 <- rep(0, 73)
g82 <- rep(6, 164)
g83 <- rep(10111, 571)
g84 <- rep(0, 217)
g85 <- rep(289, 923)
g86 <- rep(0, 2240)
g87 <- rep(0, 9)
g88 <- rep(0, 39)
g89 <- rep(0, 35)
g90 <- rep(0, 12)
g91 <- rep(29, 115)
g92 <- rep(0, 7)
g93 <- rep(0, 348)
g94 <- rep(0, 155)
g95 <- rep(0, 287)
h96 <- rep(9, 112)
h97 <- rep(0, 15)
h98 <- rep(0, 207)
h99 <- rep(492, 214)
i100 <- rep(6, 453)
i101 <- rep(87, 1521)
i102 <- rep(1, 3715)
i103 <- rep(12, 606)
i104 <- rep(22, 233)
i105 <- rep(106, 315)
i106 <- rep(0, 15)
i107 <- rep(94, 105)
i108 <- rep(2066, 601)
i109 <- rep(0, 294)
j110 <- rep(0, 48)
j111 <- rep(1024, 1097)
j112 <- rep(0, 9)
j113 <- rep(0, 96)
k114 <- rep(0, 1314)
k115 <- rep(1, 262)
k116 <- rep(0, 212)
k117 <- rep(0, 72)
k118 <- rep(0, 67)
k119 <- rep(0, 388)
l120 <- rep(0, 390)
l121 <- rep(196, 140)
l122 <- rep(4, 62)
l123 <- rep(0, 154)
l124 <- rep(0, 139)
l125 <- rep(0, 257)
l126 <- rep(0, 15)
l127 <- rep(1221, 155)
l128 <- rep(297, 46)
m129 <- rep(0, 81)
m130 <- rep(0, 266)
m131 <- rep(0, 12)
m132 <- rep(0, 303)
m133 <- rep(0, 509)
m134 <- rep(0, 22)
m135 <- rep(4, 476)
m136 <- rep(0, 16)
m137 <- rep(0, 47)
m138 <- rep(0, 22)
m139 <- rep(0, 321)
m140 <- rep(0, 19)
m141 <- rep(0, 15)
m142 <- rep(960, 1015)
m143 <- rep(0, 49)
m144 <- rep(0, 149)
m145 <- rep(0, 7)
m146 <- rep(0, 736)
m147 <- rep(0, 95)
m148 <- rep(0, 7)
m149 <- rep(1, 368)
m150 <- rep(0, 455)
m151 <- rep(0, 842)
n152 <- rep(1, 235)
n153 <- rep(0, 8)
n154 <- rep(0, 202)
n155 <- rep(528, 283)
n156 <- rep(0, 7)
n157 <- rep(0, 127)
n158 <- rep(1, 775)
n159 <- rep(1, 176)
n160 <- rep(0, 255)
n161 <- rep(3, 364)
n162 <- rep(0, 8)
n163 <- rep(0, 26)
n164 <- rep(0, 257)
n165 <- rep(0, 46)
n166 <- rep(86, 1985)
o167 <- rep(0, 243)
p168 <- rep(1, 571)
p169 <- rep(0, 21)
p170 <- rep(0, 50)
p171 <- rep(2, 246)
p172 <- rep(0, 766)
p173 <- rep(0, 257)
p174 <- rep(43, 651)
p175 <- rep(8, 1238)
p176 <- rep(0, 9)
p177 <- rep(649, 316)
p178 <- rep(15, 186)
p179 <- rep(78, 69)
q180 <- rep(0, 34)
r181 <- rep(0, 323)
r182 <- rep(0, 15)
r183 <- rep(400, 274)
r184 <- rep(2403, 7379)
r185 <- rep(0, 88)
s186 <- rep(0, 8)
s187 <- rep(0, 11)
s188 <- rep(0, 7)
s189 <- rep(0, 13)
s190 <- rep(0, 10)
s191 <- rep(0, 7)
s192 <- rep(0, 24)
s193 <- rep(0, 10)
s194 <- rep(0, 27)
s195 <- rep(0, 14)
s196 <- rep(0, 22)
s197 <- rep(0, 436)
s198 <- rep(3, 243)
s199 <- rep(96, 267)
s200 <- rep(0, 8)
s201 <- rep(0, 21)
s202 <- rep(0, 126)
s203 <- rep(0, 9)
s204 <- rep(0, 9)
s205 <- rep(0, 7)
s206 <- rep(1, 145)
s207 <- rep(6, 132)
s208 <- rep(0, 335)
s209 <- rep(0, 335)
s210 <- rep(0, 222)
s211 <- rep(0, 55)
s212 <- rep(111, 260)
s213 <- rep(0, 8)
s214 <- rep(0, 326)
s215 <- rep(2639, 448)
s216 <- rep(0, 92)
s217 <- rep(0, 447)
s218 <- rep(44, 184)
s219 <- rep(0, 38)
s220 <- rep(214, 593)
s221 <- rep(1348, 187)
s222 <- rep(0, 170)
t223 <- rep(2, 68)
t224 <- rep(0, 369)
t225 <- rep(1, 563)
t226 <- rep(0, 578)
t227 <- rep(0, 70)
t228 <- rep(0, 8)
t229 <- rep(0, 134)
t230 <- rep(0, 32)
t231 <- rep(0, 30)
t232 <- rep(2, 186)
t233 <- rep(39, 562)
t234 <- rep(0, 448)
t235 <- rep(0, 29)
u236 <- rep(0, 300)
u237 <- rep(3723, 990)
u238 <- rep(383, 678)
u239 <- rep(0, 183)
u240 <- rep(32, 157)
u241 <- rep(18364, 6514)
u242 <- rep(0, 666)
v243 <- rep(0, 168)
v244 <- rep(0, 6)
v245 <- rep(112, 567)
v246 <- rep(14, 613)
v247 <- rep(0, 42)
w248 <- rep(0, 16)
w249 <- rep(0, 229)
y250 <- rep(0, 225)
y251 <- rep(0, 469)
z252 <- rep(5, 237)

count <- c(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17,
           b18, b19, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b30, b31, b32, 
           b33, b34, b35, b36, b37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47,
           c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, d60, d61, d62, 
           d63, d64, e65, e66, e67, e68, e69, e70, e71, f72, f73, f74, f75, f76, f77,
           f78, f79, g80, g81, g82, g83, g84, g85, g86, g87, g88, g89, g90, g91, g92,
           g93, g94, g95, h96, h97, h98, h99, i100, i101, i102, i103, i104, i105, i106, 
           i107, i108, i109, j110, j111, j112, j113, k114, k115, k116, k117, k118, k119,
           l120, l121, l122, l123, l124, l125, l126, l127, l128, m129, m130, m131, m132,
           m133, m134, m135, m136, m137, m138, m139, m140, m141, m142, m143, m144, m145,
           m146, m147, m148, m149, m150, m151, n152, n153, n154, n155, n156, n157, n158,
           n159, n160, n161, n162, n163, n164, n165, n166, o167, p168, p169, p170, p171, 
           p172, p173, p174, p175, p176, p177, p178, p179, q180, r181, r182, r183, r184,
           r185, s186, s187, s188, s189, s190, s191, s192, s193, s194, s195, s196, s197,
           s198, s199, s200, s201, s202, s203, s204, s205, s206, s207, s208, s209, s210,
           s211, s212, s213, s214, s215, s216, s217, s218, s219, s220, s221, s222, t223,
           t224, t225, t226, t227, t228, t229, t230, t231, t232, t233, t234, t235, u236,
           u237, u238, u239, u240, u241, u242, v243, v244, v245, v246, v247, w248, w249,
           y250, y251, z252)

library(maps)
map.dat <- map_data("world")

map.dat$count <- count
## Plot Map

ggplot() + 
  geom_polygon(data = map.dat, aes(x=long, y=lat, group=group, fill = count), colour = "blue") +  
  scale_fill_gradient("Number of Paintings", low="white",high="red") +
  labs(x="", y="", title="Stock of Paintings by Artist Birthplace") + 
  theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),axis.text.x = element_blank(), 
        plot.title = element_text(lineheight=.8, face="bold", vjust=1))
# Question 8: The Dimensions variable lists the dimensions of each painting. Use your data manipulation skills to calculate the area of each painting (in cm’s). Create a data frame of the five largest and five smallest paintings in MOMA’s collection.

dim <- df[, c(1, 6, 13)]

library(stringr)
## Extract strings under brackets ()

test <- gsub("[\(\)]", "", regmatches(dim$Dimensions, gregexpr("\(.*?\)", dim$Dimensions)))
## Extract number sequence number, decimal point, number, whitespace, alphabetic character, number, decimal point, number, whitespace, alphabetic character, alphabetic character

test <- str_extract(test, "[[:digit:]]+[\.][[:digit:]][ \t\n\r\f\v][a-z][ \t\n\r\f\v][[:digit:]]+[\.][[:digit:]][ \t\n\r\f\v][a-z][a-z]")
## Remove all alphabetic characters

test <- gsub("[a-z]", "", test)
## Split character vector containing numbers

test <- as.data.frame(str_split_fixed(test, " ", 2))
colnames(test) <- c("One", "Two")
## Add new column to dim dataset and calculate the area of the paintings in cm2

dim$Area <- as.numeric(levels(test$One))[test$One] \* as.numeric(levels(test$Two))[test$Two]
## Order dim dataset and omit NAs

dim <- na.omit(dim[order(-dim$Area, decreasing = FALSE),])
## Extract 5 largest and 5 smallest pictures

minmax_5 <- rbind(head(dim, n = 5), tail(dim, n = 5))

**Comment by sebastianbarfort** [comment]
Nice use of `geom_freqpoly`! 

I get an error in Question 7

```
> map.dat$count <- count
Error in `$<-.data.frame`(`*tmp*`, "count", value = c(45, 45, 45, 45,  : 
  replacement has 101919 rows, data has 101913
```

and generally I think your solution to this question is inefficient. See what I did instead in the solutions post. 

Generally, you're only using the `dplyr` package for Question 7. I think it makes data manipulation tasks considerably easier so I would recommend becoming more familiar with this package. 

**APPROVED**
