### ISSUE TITLE
Group 5, Assignment 1

### ISSUE THREAD

**Issue by MDjernes** [sebastianbarfort/sds#26]
‪#‎Loading‬ potentiel packages
library("readr")
library("countrycode")
library("mapdata")
library("ggmap")
library("dplyr")
library("knitr")
library("lubridate")
library("maps")
library("ggplot2")
library("stringr")

‪#‎Q1‬
df0 = read_csv("https://raw.githubusercontent.com/…/col…/master/Artworks.csv")
‪#‎keeping‬ observations that are classified as "painting"
df = df0 %>%
filter(Classification == 'Painting')

‪#‎Q2‬
‪#‎Sorting‬ observations by date. 
df= df[order(df$DateAcquired),]
df$count=1
‪#‎summarising‬ observation by dates and creating a variable of the cumulative number of paintings.
df_bydate= df %>% group_by(DateAcquired) %>% summarise(count=sum(count))%>% 
data.frame
df_bydate$cum=cumsum(df_bydate$count)
# Creating plot. An appropriate geom could be freqpoly,

p= ggplot(data =df_bydate, aes(x=DateAcquired, y=cum, ))
p= p + geom_freqpoly(binwidth=1000, fill="red", stat="identity") + labs(x = "Time", y = "# of art acquired", title = "Cumulative number of art acquired")
plot(p)

‪#‎Q3‬
# Sorting first by "Curator" then date

dfq3=df[order(df$CuratorApproved, df$DateAcquired),]
dfq3$count=1
‪#‎To‬ create two different lines, two dataframes is needed. One with CuratorApproved=Y
‪#‎and‬ one with CuratorApproved=Y
‪#‎Dataframe‬ with CuratorApp=N
dfq3_N=dfq3 %>% filter(CuratorApproved=='N') %>% select(CuratorApproved, DateAcquired, count) %>% group_by(DateAcquired) %>% summarise(count=sum(count)) %>%
data.frame
dfq3_N$CuratorApproved='N'
dfq3_N$cum=cumsum(dfq3_N$count)
# Dataframe with CuratorApp=N

dfq3_Y=dfq3 %>% filter(CuratorApproved=='Y') %>% select(CuratorApproved, DateAcquired, count) %>% group_by(DateAcquired) %>% summarise(count=sum(count)) %>%
data.frame
dfq3_Y$CuratorApproved='Y'
dfq3_Y$cum=cumsum(dfq3_Y$count)
‪#‎Merging‬(like setting in SAS) the two dataframes
dfq3_merge= rbind(dfq3_N, dfq3_Y)
‪#‎Plotting‬ the two frames
p= ggplot(dfq3_merge, aes(x=DateAcquired, y=cum, colour=CuratorApproved))
p= p + geom_freqpoly(binwidth=100, stat="identity") + labs(x = "Time", y = "Art acquired", title = "Number of art acquired over time (cumulative)")
plot(p)

‪#‎Q4‬
dfq4 = df %>%
select(DateAcquired, count, Department) %>% 
group_by(DateAcquired, Department) %>% summarise(count=sum(count)) %>%
data.frame
dfq4$cum=cumsum(dfq4$count)

‪#‎Q5‬. 
‪#‎Dataframes‬ with Departments. 
dfq4_1=df %>% filter(Department=='Fluxus Collection') %>% 
select(Department, CuratorApproved, DateAcquired, count) %>% group_by(DateAcquired) %>% 
summarise(count=sum(count)) %>%
data.frame
dfq4_1$Department='Fluxus Collection'
dfq4_1$cum=cumsum(dfq4_1$count)
dfq4_2=df %>% filter(Department=='Media and Performance Art') %>% 
select(Department, CuratorApproved, DateAcquired, count) %>% group_by(DateAcquired) %>% 
summarise(count=sum(count)) %>%
data.frame
dfq4_2$Department='Media and Performance Art'
dfq4_2$cum=cumsum(dfq4_2$count)
dfq4_3=df %>% filter(Department=='Painting & Sculpture') %>% 
select(Department, CuratorApproved, DateAcquired, count) %>% group_by(DateAcquired) %>% 
summarise(count=sum(count)) %>%
data.frame
dfq4_3$Department='Painting & Sculpture'
dfq4_3$cum=cumsum(dfq4_3$count)
dfq4_4=df %>% filter(Department=='Prints & Illustrated Books') %>% 
select(Department, CuratorApproved, DateAcquired, count) %>% group_by(DateAcquired) %>% 
summarise(count=sum(count)) %>%
data.frame
dfq4_4$Department='Prints & Illustrated Books'
dfq4_4$cum=cumsum(dfq4_4$count)
# Merging datasets

dfq4_merge= rbind(dfq4_1, dfq4_2, dfq4_3, dfq4_4)
p= ggplot(dfq4_merge, aes(x=DateAcquired, y=cum, colour=Department))
p= p + geom_point(binwidth=100, stat="identity") + labs(x = "Department", y = "Art acquired", title = "Number of art acquired by department")
plot(p)

‪#‎Q6‬
‪#‎Creating‬ data frame grouping by artist. Removing missings so they don't count.
dfq6 = df %>%
group_by(Artist) %>%
summarise(count = sum(count)) %>%
filter(Artist>0) %>%
data.frame
# sorting by count.

dfq6= dfq6[order(dfq6$count, decreasing = TRUE ),]
‪#‎printing‬ top 10
head(dfq6,10)

‪#‎Q7‬
‪#‎Cleaning‬ the observations and keeping only a bithplace
dfq7=df 
dfq7$bp1=str_extract(dfq7$ArtistBio, "born [A-z]*")
dfq7$bp1=gsub("born ","", dfq7$bp1)
dfq7$bp2=str_extract(dfq7$ArtistBio, "[A-z]+")
dfq7$bp1[is.na(df$b1)]=dfq7$bp2[is.na(df$b1)]
‪#‎reading‬ dataset, which contains birthplace and country codes, as the country code function didn't work.
‪#‎There is most llikely an alternative to this question, since we are using a 'private' cvs. data fil.
# This will not run if pasted directly to another computer - depends on an extra file

dfq7cc= read.csv("\Users\Ejer\Dropbox\Uni\Social Data Science\assign1\Countries-List.csv")
‪#‎countrycode‬(df$bc, origin = "country.names", destination = "iso2c")
‪#‎changing‬ the class from factor to character
Countries.List$isocode <- as.character(Countries.List$V1)
Countries.List$bp2 <- as.character(Countries.List$V2)
# Merging the dataframe with countrycodes

dfq7_merge=left_join(dfq7,Countries.List, by ='bp2')
df7.fin=dfq7_merge %>%
group_by(isocode) %>%
summarise(count = sum(count)) %>%
data.frame
# Loading map data

map = map_data("world")
# Creating variable of country code and long-latitudes

map$isocode = countrycode(map$region, origin = "country.name", destination = "iso2c")
# merging dataframe and map data by countrycodes

df7.final=left_join(map, df7.fin, by = 'isocode' )
# Creating world map. Grey countries has no observations. Difficult to spot the difference
# in countries outside US.

p = ggplot(df7.final, aes(x = long, y = lat, group = group)) +
geom_polygon(aes(fill = count)) +
expand_limits() +
theme_minimal()
plot(p)
# Q8
# Extracting measures

dfq8=df
dfq8$size=str_extract(df$Dimensions, "([0.0-9.9]+ x [0.0-9.9]+ cm)")
dfq8$size1=gsub("x [0.0-9.9]+ cm","", df$size)
dfq8$size1=as.numeric(df$size1)
dfq8$size2=gsub("[0.0-9.9]+ x","", df$size)
dfq8$size3=gsub("cm","", df$size2)
dfq8$size3=as.numeric(df$size3)
# Calculating size

dfq8$area=df$size1*df$size3
# Listing top and bottom 5

dfq8= dfq8[order(df$area, decreasing = TRUE),]
head(df$Artist,5)
head(df$`﻿Title`)
dfq8= dfq8[order(df$area, decreasing = FALSE),]
head(df$Artist,5)
head(df$`﻿Title`)

**Comment by sebastianbarfort** [comment]
I can't read your data in Q1. Please update your code and resubmit.

**Comment by mathiasdalsten** [comment]
Sorry. It somehow shortned the link. This should work:
#Q1
df0 = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
‪#‎keeping‬ observations that are classified as "painting"
df = df0 %>%
  filter(Classification == 'Painting')

**Comment by sebastianbarfort** [comment]
Generally a good assignment.

Nice use of `freqpoly`

Try as far as possible to make the file run on any computer. That is, for external files, try and upload them to github and load them as we've done in class. 

For ordering I would recommend the `arrange` function in `dplyr`. I find it easier to work with than `order`. 

**APPROVED**
