### ISSUE TITLE
Group 27: Assignment 1

### ISSUE THREAD

**Issue by vstentoft** [sebastianbarfort/sds#3]
## ASSIGNMENT 1 - GROUP 27

rm(list=ls())
# Loading packages (used in mentioned order)

library("readr")
library("lubridate")
library("dplyr")
library("ggplot2")
library("zoo")
library("ggplot2")
library("maps")
library("countrycode")
library("stringr")
# Data input ----

df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
# Prepare data: from the 'DateAcquired' column we create two column stating year and month

df$year = year(df$DateAcquired)
df$month = month(df$DateAcquired)
# All NA's are removed

df.Q15 = df %>% 
    filter(!is.na(df$DateAcquired)) %>%
    arrange(DateAcquired)
# Question 1 ----
# The data is grouped by year and month and counted cumulatively

df.stock = df.Q15 %>%
    count(year, month) %>%
    group_by(year, month) %>%
    arrange(year)
df.stock$cum = cumsum(df.stock$n)
# Question 2 ----
# Creating a usable time-column to use as x-axis in the plot of stock af painting over time

df.stock$ym = as.Date(as.yearmon(paste(df.stock$year, df.stock$month, sep = "-")))
# Plotting cumulated number of paintings against time

p = ggplot(df.stock, aes(x = ym, y = cum)) +
    geom_area(stat = "identity", colour = "red", fill = "red") +
    theme_minimal() +
    labs(x = "Years", y = "Stock",
          title = "The stock af paintings at MoMa since its opening")
plot(p)
# Since the stock of paintings is continous, we think that the geom_area is an appropriate choice of geom. You could use geom_line, however since it is a stock, that an area plot visualizes the data better.
# Question 3 ----
# Manipulating data to cumulatively sum over CuratorApproved

df.ca = df.Q15 %>%
  count(CuratorApproved, year) %>%
  group_by(CuratorApproved) %>%
  mutate(sum = order_by(CuratorApproved, cumsum(n))) %>%
  arrange(year)
# Plotting data

p = ggplot(df.ca, aes(x = year, y = sum, fill = CuratorApproved)) +
  geom_area(stat = "identity") +
  theme_minimal() +
  labs(x = "Years", y = "Stock",
       title = "The stock af paintings curator approved and non-approved at MoMa since its opening")
plot(p)
# Question 4 ----
# Manipulating data to show the stock of paintings for each department

df.dep = df.Q15 %>%
  count(Department, year, month) %>%
  group_by(Department) %>%
  mutate(sum = order_by(Department, cumsum(n))) %>%
  mutate(ym = as.Date(as.yearmon(paste(year, month, sep = "-"))))
# Question 5 ----
# Plotting the data depending on Department

p = ggplot(df.dep, aes(x = ym, y = sum, group = Department, colour = Department)) +
    geom_line() + 
    theme_minimal()
  plot(p)  
# Prints & Illustrated Books has had the highest increase in their stock of paintings
# Question 6 ----
# Counting the number of contributions from each painter and listing the 10 artists with the most contributions

df.art = df %>%
    filter(!is.na(Artist) & Artist != "") %>%
    count(Artist) %>%
    arrange(desc(n))
head(df.art, 10)
# Question 7 ----

df.bp = df %>%
  filter(!is.na(Artist) & Artist != "") %>%
  filter(!is.na(ArtistBio) & ArtistBio != "") %>%
  count(Artist, ArtistBio) %>%
  arrange(desc(n))
# Worldmap

map = map_data("world")
# Add countrycodes with two characters

library("countrycode")
map$iso2c = countrycode(map$region, origin = "country.name", destination = "iso2c")
# Deleting signs with gsub and use str_extract to get the nationality of artits

library("stringr")
df.bp$Bio = gsub("\(|\)", "", df.bp$ArtistBio)
df.bp$Bio = str_extract(df.bp$Bio, "[A-Z].[a-z]+")
df.bp = df.bp %>%
  filter(Bio != "Nationality" & Bio != "Various")
# Change nationality to country through a loop

from = c("Filipino", "Israeli","Afghan","Albanian","Algerian","Andorran","Angolan","Argentine","Armenian","Australian","Austrian","Azerbaijani","Bahamian","Bahraini","Banglade","Barbadian","Belgian","Belizean","Beninese","Bhutanes","Bolivian","Bosnian","Botswanan","Brazilian","British","Bruneian","Bulgarian","Burkines","Burmese","Burundia","Cambodian","Cameroonian","Canadian","Chilean","Chinese","Colombian","Congolese","Costa","Croatian","Cuban","Czech","Danish","Djiboutian","Dominican","Dominica","Ecuadorian","Egyptian","Salvador","English","Eritrean","Estonian","Ethiopian","Fijian","Finnish","French","Gabonese","Gambian","Georgian","German","Ghanaian","Greek","Grenadia","Guatemalan","Guinean","Guyanese","Haitian","Dutch","Honduran","Hungarian","Icelandic","Indian","Indonesian","Iranian","Iraqi","Irish","Italian","Jamaican","Japanese","Jordania","Kazakhstani","Kenyan","Kuwaiti","Laotian","Latvian","Lebanese","Liberian","Libyan","Lithuanian","Luxembourgish","Macedonian","Malawian","Malaysian","Maldivian","Malian","Maltese","Mauritanian","Mauritian","Mexican","Moldovan","Mongolian","Montenegrin","Moroccan","Mozambican","Namibian","Nepalese","Dutch","New","Nicaraguan","Nigerien","Nigerian","Norwegian","Omani","Pakistani","Panamanian","Paraguayan","Peruvian","Polish","Portuguese","Romanian","Russian","Rwandan","Saudi","Scottish","Senegalese","Serbian","Singaporean","Slovak","Slovenian","Somali","South","Korean","Spanish","Sri Lankan","Sudanese","Surinamese","Swazi","Swedish","Swiss","Syrian","Taiwanese","Tajik","Tanzanian","Thai","Tunisian","Turkish","Ugandan","Ukrainian","British","American","Uruguayan","Uzbek","Vanuatuan","Venezuelan","Vietnamese","Yugoslav","Zambian","Zimbabwean")
to = c("Phillippines", "Israel", "Afghanistan","Albania","Algeria","Andorra","Angola","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belgium" , "Belize" , "Benin" , "Bhutan" ,"Bolivia" ,"Bosnia-Herzegovin" , "Botswana" , "Brazil" , "Britain" , "Brunei" , "Bulgaria" , "Burkina" , "Burma" , "Burundi" , "Cambodia" , "Cameroon" , "Canada" , "Chile", "China", "Colombia" , "Congo","Costa Rica", "Croatia", "Cuba", "Czech Republic", "Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador", "Britain", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambiahe", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea","Guyana","Haiti","Holland","Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kuwait", "Laos", "Latvia", "Lebanon", "Liberia", "Libya", "Lithuania", "Luxembourg", "Macedonia", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Mauritania", "Mauritius", "Mexico", "Moldova", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Namibia", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Panama", "Paraguay", "Peru", "Poland", "Portugal", "Romania", "Russia", "Rwanda", "Saudi Arabia","Scotland", "Senegal", "Serbia", "Singapore", "Slovakia", "Slovenia", "Somalia", "South Africa","South Korea", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Tunisia", "Turkey", "Uganda", "Ukraine", "Britain", "USA", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela","Vietnam", "Yugoslavia", "Zambia","Zimbabwe")
for (i in 1:156){
  df.bp$Bio[df.bp$Bio == from[i]] = to[i]
}
# Removing NA's and blanks and rename country to iso2c-encoding

df.bp = df.bp %>%
  filter(Bio != "Nationality" & Bio != "Various") %>%
  filter(!is.na(Bio))
df.bp$iso2c = countrycode(df.bp$Bio, origin = "country.name", destination = "iso2c")
# Counting number of contributions from each country

df.bp = df.bp %>%
  count(iso2c)
# Joining dataframes containing number of paintings per country and longitude and latitude data

df.map = full_join(df.bp, map)
# Plotting the data on a world map and adjusting colors according to the log og number of painting per country

p = ggplot(df.map, aes(x = long, y = lat, group = group, fill = log(n)))
p + geom_polygon() + scale_fill_continuous(low="thistle2", high="darkred", guide="colorbar", na.value="grey") +
  expand_limits(x = df.map$long, y = df.map$lat) +
  labs(title = "MOMA's Stock of Paintings: Nationality of Author - World Map (log)")
# Question 8 ----
# Selecting relevant variables

df.dim = df %>%
  select(Dimensions, Artist, `<ef><bb><bf>Title`) %>%
  filter(!is.na(Dimensions))
# Extracting the relevant string from variables

df.dim$ext = str_extract(df.dim$Dimensions, "\([^()]+\)")
df.dim$ext = gsub("\(|\)", "", df.dim$ext)
df.dim$ext = gsub(" cm", "", df.dim$ext)
# Removing the remaining NA's and foul format numbers

df.dim = df.dim %>%
  filter(!is.na(ext) & is.na(as.numeric(ext)))
# Getting height and length of each painting

df.dim$h = as.numeric(gsub(" [x X] [0-9].+", "", df.dim$ext))
df.dim$l = as.numeric(gsub("[0-9]+.[0-9] [x X]", "", df.dim$ext))
# Calculating the area of each contribution in cm^2

df.dim = df.dim %>%
  filter(!is.na(h) & !is.na(l)) %>%
  mutate(area = h \* l) %>%
  arrange(desc(area))
# Creating a data frame of the five largest and smallest paintings

df.dim.maxmin = rbind(head(df.dim, 5), tail(df.dim, 5))

**Comment by sebastianbarfort** [comment]
Hi, this looks like a very nice assignment, but I can't read your files as the path refers to something locally on your computer. Can you email me the data so I can run the code?

**Comment by sebastianbarfort** [comment]
Overall it's a good assignment. 

I get an error in question 8, so take a look at your code and make sure you understand why (and check my solution). 

**APPROVED**

**Comment by vstentoft** [comment]
Hi Sebastian,

The error is due to my encoding problems, that I am still working on. If you insert the right name for the title column it should be fine (I can’t check what the actual name is). Find the code and the problem in bold below.

# Question 8 ----

#Selecting relevant variables
df.dim = df %>%
  select(Dimensions, Artist, `<ef><bb><bf>Title`) %>%
  filter(!is.na(Dimensions))

#Extracting the relevant string from variables
df.dim$ext = str_extract(df.dim$Dimensions, "\([^()]+\)")
df.dim$ext = gsub("\(|\)", "", df.dim$ext)
df.dim$ext = gsub(" cm", "", df.dim$ext)

#Removing the remaining NA's and foul format numbers
df.dim = df.dim %>%
  filter(!is.na(ext) & is.na(as.numeric(ext)))

#Getting height and length of each painting
df.dim$h = as.numeric(gsub(" [x X] [0-9].+", "", df.dim$ext))
df.dim$l = as.numeric(gsub("[0-9]+.[0-9] [x X]", "", df.dim$ext))

#Calculating the area of each contribution in cm^2
df.dim = df.dim %>%
  filter(!is.na(h) & !is.na(l)) %>%
  mutate(area = h \* l) %>%
  arrange(desc(area))

#Creating a data frame of the five largest and smallest paintings
df.dim.maxmin = rbind(head(df.dim, 5), tail(df.dim, 5))

**Comment by sebastianbarfort** [comment]
Thanks so much!
