### ISSUE TITLE
Group 001: Assignment 1

### ISSUE THREAD

**Issue by hjalager** [sebastianbarfort/sds#7]
# Assignment 1 - 14. okt. 2015
# Group 1 (Kasper, Stine, Nynne)
###### 
# Intro
# Required packages for the assignment are loaded

library("readr")
library("stringr")
library("lubridate")
library("dplyr")
library("ggplot2")
library("maps")
# read the data

moma = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")
problems(moma)
# problem: rows with wrong date format:
# row   col           expected     actual
# (int) (int)              (chr)      (chr)
#1  97640    11 date like %Y-%m-%d 11-17-2009
#2  99556    11 date like %Y-%m-%d 11-17-2009
#3  99557    11 date like %Y-%m-%d 11-17-2009
#4  99558    11 date like %Y-%m-%d 11-17-2009
#5  99559    11 date like %Y-%m-%d 11-17-2009
#6 119480    11 date like %Y-%m-%d       1941
# We remove the rows with problems (easiest choice, could also mutate them to correct data format)

moma = moma[-problems(moma)$row,]
# 
# summary data

dim(moma)
# dimensions in df:
#123913 x 14, i.e. 14 variables and 123913 objects

names(moma)
# names of the variables:
# [1] "?Title"        "Artist"          "ArtistBio"       "Date"
# [5] "Medium"          "Dimensions"      "CreditLine"      "MoMANumber"
# [9] "Classification"  "Department"      "DateAcquired"    "CuratorApproved"
# [13] "ObjectID"        "URL"

head(moma, 3)
# looking at the first three data rows
# 
# 
# Question 1 - Create a new dataframe of the stock of paintings
# at MOMA for each month in the year.
# 
# table to see the different classificatons and the name of the painting class

table(moma$Classification)
# We create a df for paintings:

library("dplyr")
momap = moma %>%
  filter(Classification == "Painting", TRUE)
# df named momap for moma paintings

dim(momap)
#2229 x 14
# i.e. 2229 of the 123913 objects are paintings
# 
# creates two new variables for which year and month the painting is acquired.

momap$Month = format(momap$DateAcquired,"%Y-%m-01")
momap$Year = format(momap$DateAcquired,"%Y-01-01")
# It is only the "Month" variable which is required for Q.2 and Q.3
# We use dplyr to make a new dataframe for paintings in each month(only months with paintings are included):

momap_date = momap %>% 
  group_by(Month) %>%
  summarize(count=n())
# 
# 
###### 
# Question 2 - Use ggplot2 and your new data frame to plot the the stock
# of paintings on the y-axis and the date on the x-axis.
# 

library("ggplot2")
p = ggplot(momap_date, aes(x = as.Date(Month), y = count))
p = p + geom_bar(stat="identity",colour="red") + labs(x="Time", y="Stock of paintings", title = "Paintings at MoMA over time")
p = p + theme_minimal()
plot(p)
# The bardiagram(or histogram) is appropiate to show the number of paintings over time,
# easy to see the distribution for a large number of painting over a long periode.
# 
# 
###### 
# Question 3 - Create the same plot but this time the color should reflect
# the stockof paintings for curator approved and non-curator
# approved paintings, respectively.
# 
# Create a new dataframe just like in Q.2 but this time also conditioning on if painting is Curator approved

momap_cur = momap %>% 
  group_by(Month, CuratorApproved) %>%
  summarize(count=n())
# Creates bardiagram for curator approved and not curatorapproved

q = ggplot(momap_cur, aes(x = as.Date(Month), y = count, colour=CuratorApproved))
q = q + geom_bar(stat="identity") + labs(x="Time", y="Stock of paintings", 
                                     title = "Number of Curator Approved Paintings Over Time") + theme_minimal()
plot(q)
# to see the number of yes' and nos:

table(momap$CuratorApproved)
# No: 234, Yes: 1995
# 
# 
###### 
# Question 4 - Create a new dataframe of the stock of paintings grouped
# by what department the painting belongs to.
# 

momapd = momap %>%
  group_by(Department)
# named nomapd for noma paintings at departments
# the departments with paintingS:

table(momapd$Department)
# Fluxus Collection     Media and Performance Art       Painting & Sculpture
#6                          4                           2193
# Prints & Illustrated Books
#26
# 
# The department with most paintings is 'Painting & Sculpture'
# 
# 
###### 
# Question 5 - Plot this data frame using ggplot2. Which department has had
# the highest increase in their stock of paintings?
# 
# Histograms - number of paintings over time by department:

b = ggplot(momapd, aes(x = DateAcquired))
b = b + geom_histogram()
b = b + facet_wrap(~ Department, scales = "free") #make separate plot for each department
b = b + labs(x = "Date", y = "Number",
             title = "Number of Paintings Over Time by Department") #make nice titles
plot(b)
# 
# The department of 'Painting & Sculpture" has the highest number
# of paintings over time
# 
# 
###### 
# Question 6 - Write a piece of code that counts the number of paintings by each
# artist in the dataset. List the 10 painters with the highest number
# of paintings in MOMA's collection.
# 

momapa = momap %>%
  group_by(Artist)
# named nomapa for noma paintings by artists
# 

w = table(momapa$Artist)  #table the artists and their number of paintings
t = as.data.frame(w) #save it as a df with name t
names(t)[1] = 'Artist_name' #naming the first variable in the df t 'artist_name'
head(t, 10) # just checking out the df t
m = t[order(t$Freq, decreasing = TRUE, na.last = NA) , ] #order the artists with most paintings first
head(m, 10) # success! showing the ten artists with most paintings:
# Artist_name Freq
#702  Pablo Picasso   55
#367  Henri Matisse   34
#693      On Kawara   32
#406 Jacob Lawrence   30
#433  Jean Dubuffet   25
#688   Odilon Redon   25
#120    Ben Vautier   24
#283   Frank Stella   23
#732  Philip Guston   23
#452     Joan Miró   20
# 
# 
###### 
# Question 7
# Renaming the dataset from momap to paint

paint=momap
# taking stock of the data that we're about to extract

head(paint$ArtistBio,5)
# grabing letters from A-Z and stopping at ","

paint$Demonym.1 <- str_extract (paint$ArtistBio, "[A-z]*, ")
# substracting the comma away from the observations

paint$Demonym.1 <- gsub(", ", "", paint$Demonym.1)
# regrouping in a new dataset and removing NA's

paint.birth <- tally(group_by(paint, Demonym.1))
paint.birth <- paint.birth[complete.cases(paint.birth),]
# We found a dataset online (provided by a fellow student from another group)
# which contains both nationality and nation, which we can use to find the country

ccode <- read.csv("http://t2a.co/blog/wp-content/uploads/2014/03/Countries-List.csv", header=TRUE, stringsAsFactors=FALSE, fileEncoding="latin1")
# merging artists birth with the ccode by nationality

countries <- merge(paint.birth, ccode, by="Demonym.1")
# changing column Name to region and setting Demonym.2 and .3 to null

countries$Demonym.2 <-NULL
countries$Demonym.3 <-NULL
names(countries) <- c("Demonym.1","n","ISO","region")
# removing all the nonexisting nationalities

countries <- countries[which(!countries$Demonym.1 %in% ""),]
countries <- countries[which(!countries$region %in% "Congo (Republic of)"),]

sum(paint.birth$n) # 2221
sum(countries$n) #2209 
# we've lost 12 observations in the cleaning process, which will have to do
# making the world map

map <- map_data("world")
# it seems our vectors do not have the same class, which wont do

class(countries$region)
class(map$region)
countries$region <- as.character(countries$region)
# we can now merge our df together and check if all is well

paint.map1 <- left_join(countries, map, by="region")
subset(paint.map1, is.na(paint.map1$long))
#8 countries aren't asigned rightfully, manual manipulation will have to do

countries$region <- gsub("United States of America", "USA", countries$region)
countries$region <- gsub("United Kingdom", "UK", countries$region)
countries$region <- gsub("Democratic Republic of the Congo", "Congo", countries$region)
countries$region <- gsub("Croatia", "Yugoslavia", countries$region) #apparently the map is super old
countries$region <- gsub("Czech Republic", "Czechoslovakia", countries$region)
countries$region <- gsub("Russian Federation", "USSR", countries$region)
countries$region <- gsub("South Sudan", "Sudan", countries$region)
countries$region <- gsub("Ukraine", "Hungary", countries$region)

paint.map1 <- left_join(countries, map, by="region")
subset(paint.map1, is.na(paint.map1$long))
# everything seems to be working allright
# we want the full map database, so right_join is the way to go

paint.map2 <- right_join(countries, map, by = "region") 
# We then construct the world map

p = ggplot(paint.map2, aes(x = long, y = lat, group = group, fill = n))
p + geom_polygon() 
###### 
# Question 8
# examining the painting dimension

head(paint$Dimensions)
# grabing letters from A-Z and stopping at ","

paint$cm <- str_extract (paint$Dimensions, "(\([0-9]*)+(.)+([0-9])")
paint$cm <- gsub("\(", "", paint$cm)
# making two columns in order to find the product of the two

paint$he <- lapply(strsplit(as.character(paint$cm), "x"), "[", 1)
paint$wi <- lapply(strsplit(as.character(paint$cm), "x"), "[", 2)
# if width is missing we'll assume that the cm^2 is already in the collumn

paint$wi[is.na(paint$wi)] <- 1
# making sure vairables are numereic

paint$wi <- as.numeric(paint$wi)
paint$he <- as.numeric(paint$he)
paint$sum <- paint$he*paint$wi #creating the painting size
# renaming the column title in order to work with it

colnames(paint)[1] <-"title"
# the new dataset only contains the Artist, title and size of the painting

sum <-paint %>% select(Artist, title, sum) %>% arrange(-sum) 
# For some reason Year and Month didnt get erased from df

sum$Year <- NULL
sum$Month <- NULL

sum <- sum[complete.cases(sum),] # removing na's
# showing biggest and smallest paintings

head(sum,5)
tail(sum,5)

**Comment by sebastianbarfort** [comment]
I think this is a good assignment. 

Generally I think it's a good idea to use lineplots instead of histograms when you plot a variable over time. 

Very very good comments. 

**APPROVED**
