### ISSUE TITLE
Group 011: Assignment 1

### ISSUE THREAD

**Issue by jobrunjohansen** [sebastianbarfort/sds#9]
# Assignment 1
# Datasættet indlæses

library("readr")
df = read_csv("https://raw.githubusercontent.com/MuseumofModernArt/collection/master/Artworks.csv")

library("plyr") #skal indlæses før dplyr (bruges i sp. 7)
# Question 1
# Vha. pakkerne "dplyr" og "zoo" dannes et nyt datasæt "df2", som bl.a. indeholder variablerne "Month" og "AccNumber"
# "Month" indeholder måneder pr. år, mens "AccNumber" indeholder bestanden af malerier hver måned

library("dplyr")
library("zoo")
df2 = df %>%
  filter(!is.na(as.numeric(DateAcquired))) %>% # fjerner alle de manglende observationer i "DateAquired"
  filter(as.numeric(DateAcquired) !="") %>% # fjerner alle de tomme celler i "DateAquired"
  mutate(Month=as.yearmon(DateAcquired)) %>% # danner en ny variable "Month", som er lig med måned og år på baggrund af "DateAquired"
  group_by(Month) %>% # grupperer efter "Month"
  summarise(Number = n()) %>% # summerer antallet af malerier hver måned
  mutate(AccNumber = cumsum(Number)) # danner en ny variabl "AccNumber", som er lig det akkumulerede antal malerier hver måned, dvs. bestanden af malerier hver måned
# Question 2
# Vha. pakken "ggplot2" og datasættet "df2" plottes bestanden af malerier på y-aksen og tiden på x-aksen

library("ggplot2")
p = ggplot(data = df2, aes(x = as.numeric(Month), y = AccNumber)) # tilføjer data til et plot
p = p + geom_point(stat = "identity", size = 1, colour = "red") # tilføjer et punktdiagram, hvor prikkerne er røde i str. 1
p = p + labs(title = "The stock of paintings each month in the year", x = "Time", y = "The stock of paintings") # tilføjer en titel og personlige akser
p
# Punktdiagrammet er valgt, da det tydeligt viser udviklingen i bestanden af malerier hver måned
# Question 3
# Vha. pakkerne "dplyr" og "zoo" dannes et nyt datasæt "df3", som bl.a. indeholder variablerne "Month", "AccNumber" og "CuratorApproved"
# "Month" indeholder måneder pr. år, "AccNumber" indeholder bestanden af malerier opdelt efter kuratorstatus hver måned, og "CuratorApproved" indeholder kuratorstatus
# Vha. pakken "ggplot2" og datasættet "df3" plottes bestanden af malerier opdelt efter kuratorstatus på y-aksen og tiden på x-aksen

library("dplyr")
library("zoo")
df3 = df %>%
  filter(!is.na(as.numeric(DateAcquired))) %>% # fjerner alle de manglende observationer i "DateAquired"
  filter(as.numeric(DateAcquired) !="") %>% # fjerner alle de tomme celler i "DateAquired"
  filter(CuratorApproved %in% c("Y", "N")) %>% # opdeler variablen "CuratorApproved" i "Y" og "N", dvs. ja og nej
  mutate(Month=as.yearmon(DateAcquired)) %>% # danner en ny variable "Month", som er lig med måned og år på baggrund af "DateAquired"
  group_by(CuratorApproved, Month) %>% # grupperer efter "CuratorApproved" og "Month"
  summarise(Number = n()) %>% # summerer antallet af malerier opdelt efter kuratorstatus hver måned
  mutate(AccNumber = cumsum(Number)) # danner en ny variabl "AccNumber", som er lig det akkumulerede antal malerier opdelt efter kuratorstatus hver måned, dvs. bestanden af malerier opdelt efter kuratorstatus hver måned

library("ggplot2")
p = ggplot(data = df3, aes(x = as.numeric(Month), y = AccNumber, color = CuratorApproved)) # tilføjer data til et plot, som skal farves efter "CuratorApproved"
p = p + geom_point(stat = "identity", size = 1) # tilføjer et punktdiagram, hvor prikkerne er i str. 1
p = p + labs(title = "The stock of paintings divided by curator status each month in the year", x = "Time", y = "The stock of paintings") # tilføjer en titel og personlige akser
p
# Question 4
# Vha. pakkerne "dplyr" og "zoo" dannes et nyt datasæt "df4", som bl.a. indeholder variablerne "Month", "AccNumber" og "Department"
# "Month" indeholder måneder pr. år, "AccNumber" indeholder bestanden af malerier opdelt efter afdeling hver måned, og "Department" indeholder afdelinger

library("dplyr")
library("zoo")
df4 = df %>%
  filter(!is.na(as.numeric(DateAcquired))) %>% # fjerner alle de manglende observationer i "DateAquired"
  filter(as.numeric(DateAcquired) !="") %>% # fjerner alle de tomme celler i "DateAquired"
  mutate(Month=as.yearmon(DateAcquired)) %>% # danner en ny variable "Month", som er lig med måned og år på baggrund af "DateAquired"
  group_by(Department, Month) %>% # grupperer efter "Department" og "Month"
  summarise(Number = n()) %>% # summerer antallet af malerier opdelt efter afdeling hver måned
  mutate(AccNumber = cumsum(Number)) # danner en ny variabl "AccNumber", som er lig det akkumulerede antal malerier opdelt efter afdeling hver måned, dvs. bestanden af malerier opdelt efter afdeling hver måned
# Question 5
# Vha. pakken "ggplot2" og datasættet "df4" plottes bestanden af malerier opdelt efter afdeling på y-aksen og tiden på x-aksen

library("ggplot2")
p = ggplot(data = df4, aes(x = as.numeric(Month), y = AccNumber, color=Department)) # tilføjer data til et plot, som skal farves efter "Department"
p = p + geom_line(stat = "identity") # tilføjer et stregdiagram
p = p + labs(title = "The stock of paintings divided by department each month in the year", x = "Time", y = "The stock of paintings") # tilføjer en titel og personlige akser
p
# Jf. plottet har afdelingen "Architecture & Design" haft den største stigning i deres bestand af malerier
# Question 6
# Vha. pakkerne "dplyr" og "zoo" dannes et nyt datasæt "df5", som bl.a. indeholder variablerne "Artist" og "Number"
# "Artist" indeholder navnene på malerne, mens "Number" indeholder antallet af malerier, som hver maler har malet

library("dplyr")
library("zoo")
df5 = df %>%
  filter(!is.na(Artist)) %>% # fjerner alle de manglende observationer i "Artist"
  filter(Artist !="" ) %>% # fjerner alle de tomme celler i "Artist"
  group_by(Artist) %>% # grupperer efter "Artist"
  summarise(Number = n()) %>% # summerer antallet af malerier pr. maler
  arrange(desc(Number)) # arrangerer "Number" efter aftagende værdier
head(df5, 10) # lister de 10 malere, som har malet flest malerier
# Question 7
# Bemærk at det antages, at det første land i "ArtistBio" er fødelandet

df$count_country = 1#laver en variabel til at summere senere

library(stringr)
df$bio <- word(df$ArtistBio,1) #Ny variabel der er det første ord i ArtistBio
df$cntry <- str_extract(df$bio, "[a-zA-Z]+") #Nu kun med bogstaver
# Ny data frame

df7 <- df[,c("cntry","count_country")]
# library("plyr")
# Renser data med revalue, således de kan grupperes og joines med et standard datasæt i rworldmap

df7$cntry <- revalue(df7$cntry, c("American"="USA","Anglo"="Irish","British"="UK","Barcelona"="Spanish","Canadian"="Canada"
                                  ,"Catalan"="Spanish","Chinese"="China","Cuban"="Cuba","Columbian"="Colombian","Congolese"="Congo","Czechoslovakian"="Czech","Danish"="Denmark"
                                  ,"Dutch"="Netherlands","English"="UK","Filipino"="Philippines","French"="France","Finish"="Finnish","German"="Germany"
                                  ,"Greek"="Greece","Guyanese"="Guinea","Icelandic"="Iceland","Iraqi"="Iraq","Italian"="Italy","Ivorian"="Ivory Coast"
                                  ,"Iranian"="Iran","Japanese"="Japan","Norwegian"="Norway","Nowegian"="Norway","Osaka"="Japan","Korean"="S. Korea","Malian"="Mali"
                                  ,"Scottish"="UK","Slovak"="Slovakian","South"="South African","Swedish"="Sweden","Swiss"="Switzerland","Peruvian"="Peru","Polish"="Poland"
                                  ,"Thai"="Thailand","Turkish"="Turkey","Ukranian"="Ukrainian","Vietnamese"="Vietnam","Yugoslav"="Yugoslavian","Welsh"="UK","Zagreb"="Croatian"))
df7$cntry <- revalue(df7$cntry, c("Finnish"="Finland","Irish"="Ireland","Spanish"="Spain","UK"="United Kingdom","USA"="United States","Yugoslavian"="Serbian"))
# Summerer data over lande

df7.cntry_list<- ddply(df7, .(cntry), summarise, sum_country = sum(count_country))
# Sletter ikke-lande

df7.cntry_list<-df7.cntry_list[!(df7.cntry_list$cntry=="Active" | df7.cntry_list$cntry=="active" | df7.cntry_list$cntry=="born" | df7.cntry_list$cntry=="est" 
                                 | df7.cntry_list$cntry=="established" | df7.cntry_list$cntry=="founded" | df7.cntry_list$cntry=="Fred" | df7.cntry_list$cntry=="Jackson"
                                 | df7.cntry_list$cntry=="nationality" | df7.cntry_list$cntry=="Nationality" | df7.cntry_list$cntry=="Native" | df7.cntry_list$cntry=="New"
                                 | df7.cntry_list$cntry=="November" | df7.cntry_list$cntry=="The" | df7.cntry_list$cntry=="Various" | df7.cntry_list$cntry==""),]
# Ny varibel, så der kan joines uden at have renset alle for alle lande

df7.cntry_list$subname <- substr(df7.cntry_list$cntry,1,5)
# Laver en ny data frame df7 ud fra standard data i rworldmap

library("rworldmap")
data(countryExData)
sPDF <- joinCountryData2Map( countryExData )
df7.mapd <- sPDF@data[,c("NAME", "ADMIN","ISO_A3")]
# Variablen der skal joines på

df7.mapd$subname <- substr(df7.mapd$NAME,1,5)
# Merger data

df7.world = merge(df7.cntry_list, df7.mapd, by = "subname")
# Fjerner værdier der står dobbelt

df7.world<-df7.world[!(df7.world$NAME=="United States" & df7.world$sum_country=="5885"  | df7.world$NAME=="United Kingdom" & df7.world$sum_country=="54051" | df7.world$NAME=="United Arab Emirates" 
                       | df7.world$NAME=="Austria" & df7.world$sum_country=="246"  | df7.world$NAME=="Australia" & df7.world$sum_country=="1012"
                       | df7.world$NAME=="Congo (Brazzaville)" | df7.world$NAME=="Guinea Bissau" | df7.world$NAME=="Indian Ocean Ter" | df7.world$NAME=="Mauritius" | df7.world$NAME=="Niger"),]
# Indlæser data i kortet

library(rworldmap)
sPDF <- joinCountryData2Map( df7.world, joinCode="ISO_A3", nameJoinColumn ="ISO_A3" , verbose = TRUE)
library(RColorBrewer)
colourPalette <- brewer.pal(7,'Greens')
# Plotter data med nogle visuelle ændringer

mapParams <- mapCountryData(sPDF
                            ,nameColumnToPlot="sum_country" 
                            ,catMethod=c(0,100,200,500,1000,10000,25000,55000) 
                            ,colourPalette=colourPalette
                            ,mapTitle="Painters Birthplaces"
                            ,addLegend=FALSE 
)
# Kalder kortet med de visuelle ændringer og med en ny lodret forklaring over værdierne

do.call( addMapLegend, c( mapParams
                          , legendLabels="all"
                          , legendWidth=0.5
                          , horizontal=FALSE
                          , legendMar = 5 ))
# Question 8
# Bemærk at det antages, at arealet findes som produktet af de to første tal i "Dimensions"
# Dvs. der ses bort fra det tredje tal, som antages at være dybden

library("stringr")
# Ny data frame hvor der fjernes blanke observationer

df8<- df[,c("ï»¿Title","Dimensions","ObjectID")]
df8$Dimensions[df8$Dimensions==""] <- NA
df8 <- na.omit(df8) 

df8$list <- str_extract_all(df8$Dimensions, "\([^()]+\)") #Ny variabel der indeholder alt i parenteserne
df8$char <- substring(df8$list, 2, nchar(df8$list)-1) #Fjerne parenteserne  
df8$nr1 <- as.numeric(str_extract(df8$char, "(\d+\._\d_)")) #Får den første værdi

df8$spli <- strsplit(df8$char, split = " ") #splitter teksten op
df8$extr <- lapply(df8$spli, "[", 3) #Udtrækker den næste værdi i teksten  
df8$nr2 <- as.numeric(unlist(df8$extr)) #laver det om til numerisk    

df8$area <- df8$nr1 \* df8$nr2 #Udregner arealet
# Laver en data frame med top/bot 5

df8.tb <- df8[,c("ï»¿Title","ObjectID","Dimensions","area")]
library("dplyr")
df8.top = df8.tb %>%
  filter(!is.na(area)) %>%
  filter(area != "") %>%
  arrange(desc(area)) %>%
  head(.,n=5) #top 5
df8.bot = df8.tb %>%
  filter(!is.na(area)) %>%
  filter(area != "") %>%
  arrange(desc(area)) %>%
  tail(.,n=5) #bot 5
df8.tb <- rbind(df8.top, df8.bot) #joiner dem

**Comment by sebastianbarfort** [comment]
Generelt udmærket opgave. 

Et par småting: 
- brug `geom_line` istedet for  `geom_point` når I skal plotte tidsserier 
- forsøg at bruge `ggplot2` når I skal plotte kort, se hvad vi gjorde i forelæsningerne
- generelt gode kommentarer 

**GODKENDT**
